### PR TITLE
fix: mf multi version in same share key

### PR DESCRIPTION
**Pull request by ahabhgk**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
!canary

**Comment by ahabhgk** [comment]
!canary

**Comment by 2heal1** [comment]
@ScriptedAlchemy  it needs to be merged with mf@0.1.6 , maybe we can merge it to #6247  together

**Comment by ahabhgk** [comment]
Already merged

**Pull request closed without merging**
