### PR TITLE
test: update snapshot

### PR DESCRIPTION
**Pull request by siyou**
## Summary

copilot:summary

## Related issue (if exists)

<details open=true>
  <summary><h2>Walkthrough</h2></summary>

copilot:walkthrough

</details>

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
It seems that the snapshot is incorrect, which makes the ci fail.

**Comment by siyou** [comment]
The test case runs successfully on macOS. Based on the tested JavaScript file, the result on macOS should be correct.

**Comment by siyou** [comment]
> It seems that the snapshot is incorrect, which makes the ci fail.

The test case runs successfully on macOS. Based on the tested JavaScript file, the result on macOS should be correct.

**Comment by IWANABETHATGUY** [comment]
I am sorry we can't accept this pr if Ci is failed.

**Comment by siyou** [comment]
Okay, I will investigate the reason for the difference on different platforms.

**Comment by IWANABETHATGUY** [comment]
> Okay, I will investigate the reason for the difference on different platforms.

Any good news here?

**Comment by siyou** [comment]
> > Okay, I will investigate the reason for the difference on different platforms.
> 
> Any good news here?

Oh my god, has it been that long? I've been so busy that I forgot. I'll take a look this weekend.

**Comment by siyou** [comment]
> > Okay, I will investigate the reason for the difference on different platforms.
> 
> Any good news here?

It seems that the issue is caused by the use of HashMap/HashSet , which leads to unstable iterator ordering.

**Pull request closed without merging**
