### PR TITLE
chore(deps): add check-dependency-version for devDependencies

### LINKED ISSUE #5477: use consistent version of dependency
currently we don't enforce same version in our repo, which may cause install slow and unexpected runtime error like https://github.com/web-infra-dev/rspack/pull/5474, so it's very useful to use consistent version of dependency
```js
@rspack/binding-darwin-arm64 has different version: 0.5.2,0.4.0
@rspack/binding-darwin-x64 has different version: 0.5.2,0.4.0
@rspack/binding-linux-x64-gnu has different version: 0.5.2,0.4.0
@rspack/binding-win32-x64-msvc has different version: 0.5.2,0.4.0
@rspack/binding has different version: 0.5.2,0.4.0
@rspack/core has different version: 0.5.2,0.4.0
@rspack/plugin-react-refresh has different version: 0.5.2,0.4.0
@rspack/dev-server has different version: 0.5.2,0.4.0
@rspack/cli has different version: 0.5.2,0.4.0
react has different version: 18.0.0,17.0.2,18.2.0
react-dom has different version: 18.0.0,17.0.2,18.2.0
css-loader has different version: 6.8.1,5.0.1
react-refresh has different version: 0.14.0,0.13.0
postcss-loader has different version: 7.0.2,7.3.3
@napi-rs/cli has different version: 2.14.2,3.0.0-alpha.5
memfs has different version: 3.4.12,3.6.0
@swc/core has different version: 1.3.23,1.3.99
query-string has different version: 6.14.1,7.1.3
regenerator-runtime has different version: 0.13.9,0.13.11,0.11.1
@swc/helpers has different version: 0.5.3,0.5.1
yargs has different version: 17.6.2,3.10.0
webpack has different version: 5.89.0,5.76.0
vue has different version: 3.2.45,3.3.7
@babel/core has different version: 7.22.20,7.21.0,7.23.2
@babel/preset-react has different version: 7.22.15,7.18.6
babel-loader has different version: 9.1.3,9.1.2
fs-extra has different version: 11.1.1,11.1.0,10.1.0
postcss has different version: 8.4.21,8.4.23,8.4.31
@arco-design/web-react has different version: 2.29.2,2.56.1
ws has different version: 8.8.1,8.13.0,7.5.9
glob has different version: 10.3.10,7.2.3,7.1.6
source-map has different version: 0.7.4,0.6.1,0.5.7,0.1.32
terser has different version: 5.16.1,5.17.1
browserslist has different version: 4.21.4,4.21.10
enhanced-resolve has different version: 5.12.0,5.15.0
graceful-fs has different version: 4.2.10,4.2.11
json-parse-even-better-errors has different version: 3.0.0,2.3.1
zod-validation-error has different version: 1.3.1,1.2.0
concat-stream has different version: 2.0.0,1.6.2
source-map-support has different version: 0.5.21,0.5.13,0.3.3
colorette has different version: 2.0.19,2.0.20
interpret has different version: 3.1.1,2.2.0
rechoir has different version: 0.8.0,0.7.1
semver has different version: 6.3.1,7.5.1,7.3.8,6.3.0,7.5.4,2.3.2,5.7.1
express has different version: 4.18.1,4.18.2
mime-types has different version: 2.1.35,2.1.18
webpack-dev-middleware has different version: 6.0.2,5.3.3
@types/html-minifier-terser has different version: 7.0.0,6.1.0
pug has different version: 3.0.2,2.0.4
html-minifier-terser has different version: 7.0.0,6.1.0
jest-worker has different version: 29.3.1,27.5.1,29.7.0
assert has different version: 2.0.0,1.5.1
buffer has different version: 6.0.3,5.2.1,5.7.1
domain-browser has different version: 4.22.0,1.2.0
filter-obj has different version: 2.0.2,1.1.0
punycode has different version: 2.1.1,1.3.2
readable-stream has different version: 4.2.0,2.3.7,3.6.0,1.0.34
string_decoder has different version: 1.3.0,1.1.1,0.10.31
timers-browserify has different version: 2.0.12,1.4.2
util has different version: 0.12.5,0.10.4
@babel/parser has different version: 7.23.0,7.21.8
@babel/template has different version: 7.22.15,7.20.7
@babel/generator has different version: 7.23.0,7.21.5
@babel/helpers has different version: 7.23.2,7.21.0
@babel/traverse has different version: 7.23.2,7.22.5,7.21.5
node-fetch has different version: 2.6.7,3.2.10
chalk has different version: 5.3.0,5.0.1,4.1.2,2.4.2,1.1.3
@babel/types has different version: 7.23.0,7.21.5
prettier has different version: 3.2.4,2.8.8
@types/node has different version: 20.9.4,18.15.11,18.7.9,16.11.7
is-ci has different version: 3.0.1,2.0.0
rimraf has different version: 3.0.2,2.7.1
schema-utils has different version: 4.0.0,3.3.0,4.0.1,1.0.0,3.1.1,2.7.1
commander has different version: 10.0.1,9.4.0,2.20.3,7.2.0,8.3.0,4.1.1
typescript has different version: 4.9.4,5.3.3
ajv has different version: 8.12.0,8.11.0,6.12.6
core-js has different version: 3.25.0,3.26.1,3.30.1,2.6.12
js-yaml has different version: 4.1.0,3.14.1
fs-monkey has different version: 1.0.3,1.0.5
debug has different version: 4.3.4,2.6.9,3.2.7
scheduler has different version: 0.21.0,0.20.2,0.23.0,0.19.1
listr2 has different version: 5.0.6,4.0.5
@babel/preset-typescript has different version: 7.18.6,7.22.5
tslib has different version: 2.5.0,1.14.1
boxen has different version: 5.1.2,7.0.0
arg has different version: 5.0.2,4.1.3
klona has different version: 2.0.6,2.0.5
cosmiconfig has different version: 7.1.0,8.2.0
@webassemblyjs/ast has different version: 1.11.5,1.11.1
@swc/core-win32-x64-msvc has different version: 1.3.23,1.3.99
@swc/core-linux-x64-musl has different version: 1.3.23,1.3.99
@swc/core-darwin-x64 has different version: 1.3.23,1.3.99
@swc/core-darwin-arm64 has different version: 1.3.23,1.3.99
@swc/core-win32-ia32-msvc has different version: 1.3.23,1.3.99
@swc/core-linux-arm64-musl has different version: 1.3.23,1.3.99
@swc/core-linux-x64-gnu has different version: 1.3.23,1.3.99
@swc/core-win32-arm64-msvc has different version: 1.3.23,1.3.99
@swc/core-linux-arm64-gnu has different version: 1.3.23,1.3.99
@types/estree has different version: 1.0.0,0.0.51
@webassemblyjs/wasm-edit has different version: 1.11.5,1.11.1
@webassemblyjs/wasm-parser has different version: 1.11.5,1.11.1
acorn has different version: 8.11.2,8.8.2,8.8.0,7.4.1,3.3.0,4.0.13
es-module-lexer has different version: 1.2.1,0.9.3
d3-geo has different version: 1.6.4,2.0.2,1.7.1
d3-hierarchy has different version: 1.1.9,2.0.0
d3-voronoi has different version: 1.1.4,1.1.2
compute-scroll-into-view has different version: 1.0.20,1.0.11
react-is has different version: 16.13.1,17.0.2,18.2.0
minimist has different version: 1.2.7,1.2.8
@babel/plugin-transform-modules-commonjs has different version: 7.19.6,7.22.5
path-to-regexp has different version: 1.8.0,0.1.7,2.2.1
kleur has different version: 3.0.3,4.1.5
cliui has different version: 8.0.1,2.1.0
string-width has different version: 4.2.3,5.1.2
y18n has different version: 5.0.8,4.0.3
csstype has different version: 3.1.2,2.6.21
inherits has different version: 2.0.4,2.0.3
resolve has different version: 1.22.2,1.22.1
@vue/runtime-dom has different version: 3.2.45,3.3.7
through2 has different version: 2.0.5,4.0.2
xtend has different version: 4.0.2,2.2.0,2.1.2,3.0.0,2.0.6
@babel/helper-plugin-utils has different version: 7.22.5,7.20.2
@vue/shared has different version: 3.2.45,3.3.7
@vue/compiler-dom has different version: 3.2.45,3.3.7
@vue/compiler-sfc has different version: 3.2.45,3.3.7
@vue/server-renderer has different version: 3.2.45,3.3.7
@babel/code-frame has different version: 7.22.13,7.21.4
@babel/helper-compilation-targets has different version: 7.22.15,7.21.5
@babel/helper-module-transforms has different version: 7.23.0,7.21.5,7.22.5
convert-source-map has different version: 1.8.0,2.0.0,1.1.3
json5 has different version: 2.2.3,1.0.2
@babel/helper-validator-option has different version: 7.22.15,7.18.6,7.21.0
@babel/plugin-transform-react-display-name has different version: 7.22.5,7.18.6
@babel/plugin-transform-react-jsx has different version: 7.22.15,7.19.0
@babel/plugin-transform-react-jsx-development has different version: 7.22.5,7.18.6
@babel/plugin-transform-react-pure-annotations has different version: 7.22.5,7.18.6
color-name has different version: 1.1.4,1.1.3
find-cache-dir has different version: 4.0.0,3.3.2,2.1.0
lilconfig has different version: 2.1.0,2.0.5
glob-parent has different version: 6.0.2,3.1.0,5.1.2
is-glob has different version: 4.0.3,3.1.0
quick-lru has different version: 5.1.1,4.0.1
ipaddr.js has different version: 2.0.1,1.9.1
loader-utils has different version: 1.4.2,2.0.4
serialize-javascript has different version: 4.0.0,6.0.1
@babel/helper-module-imports has different version: 7.18.6,7.22.5,7.22.15,7.21.4
globby has different version: 7.1.1,13.1.4
minimatch has different version: 3.1.2,9.0.3
p-limit has different version: 2.3.0,3.1.0,4.0.0
cross-spawn has different version: 7.0.3,6.0.5
slash has different version: 2.0.0,1.0.0,4.0.0,3.0.0
pug-walk has different version: 1.1.8,2.0.0
acorn-walk has different version: 8.2.0,7.2.0
diff has different version: 4.0.2,5.0.0
get-stream has different version: 6.0.1,4.1.0,5.2.0
electron-to-chromium has different version: 1.4.258,1.4.496
node-releases has different version: 2.0.6,2.0.13
update-browserslist-db has different version: 1.0.9,1.0.11
caniuse-lite has different version: 1.0.30001456,1.0.30001522
signal-exit has different version: 3.0.7,4.0.1
content-type has different version: 1.0.4,1.0.5
array-flatten has different version: 1.1.1,2.1.2
body-parser has different version: 1.20.0,1.20.1
content-disposition has different version: 0.5.4,0.5.2
depd has different version: 2.0.0,1.1.2
http-errors has different version: 2.0.0,1.6.3
qs has different version: 6.10.3,6.11.0
range-parser has different version: 1.2.1,1.2.0
safe-buffer has different version: 5.2.1,5.1.2
setprototypeof has different version: 1.2.0,1.1.0
statuses has different version: 2.0.1,1.5.0
pug-strip-comments has different version: 2.0.0,1.0.4
is-plain-obj has different version: 3.0.0,2.1.0
mime-db has different version: 1.52.0,1.33.0
pug-code-gen has different version: 3.0.2,2.0.3
pug-filters has different version: 4.0.0,3.1.1
pug-lexer has different version: 5.0.1,4.1.0
pug-linker has different version: 4.0.0,3.0.6
pug-load has different version: 3.0.0,2.0.12
pug-parser has different version: 6.0.0,5.0.1
pug-runtime has different version: 3.0.1,2.0.5
clean-css has different version: 5.2.0,5.3.1,4.2.4
entities has different version: 4.4.0,2.2.0
jest-util has different version: 29.4.3,29.5.0,29.7.0
supports-color has different version: 8.1.1,9.2.2,7.2.0,5.5.0,2.0.0
@babel/helper-environment-visitor has different version: 7.22.20,7.21.5
@jridgewell/trace-mapping has different version: 0.3.17,0.3.20,0.3.9
jsesc has different version: 2.5.2,0.5.0
@babel/helper-function-name has different version: 7.23.0,7.22.5,7.21.0
@babel/helper-split-export-declaration has different version: 7.22.6,7.18.6
@babel/helper-string-parser has different version: 7.22.5,7.21.5
@babel/helper-validator-identifier has different version: 7.22.20,7.19.1
to-fast-properties has different version: 2.0.0,1.0.3
pretty-format has different version: 29.7.0,29.5.0
uuid has different version: 8.3.2,3.4.0
which has different version: 3.0.0,2.0.2,1.3.1,3.0.1
json-schema-traverse has different version: 1.0.0,0.4.1
camelcase has different version: 6.3.0,7.0.1,5.3.1,1.2.1
expect has different version: 29.5.0,29.7.0
yaml has different version: 2.2.2,1.10.2
ci-info has different version: 3.3.2,2.0.0
ajv-keywords has different version: 5.1.0,3.5.2
pidtree has different version: 0.5.0,0.3.1
@jest/types has different version: 29.5.0,27.5.1,29.6.3
cli-truncate has different version: 3.1.0,2.1.0
ansi-styles has different version: 3.2.1,4.3.0,5.2.0,6.1.0,2.2.1
lodash.memoize has different version: 4.1.2,3.0.4
argparse has different version: 2.0.1,1.0.10
ms has different version: 2.1.2,2.0.0,2.1.3
strip-ansi has different version: 6.0.1,7.0.1,3.0.1
wrap-ansi has different version: 6.2.0,8.1.0,7.0.0
@babel/compat-data has different version: 7.23.2,7.21.7,7.20.14
@babel/plugin-transform-typescript has different version: 7.20.2,7.22.5
parse-json has different version: 5.2.0,4.0.0
lru-cache has different version: 6.0.0,5.1.1,10.1.0
path-type has different version: 4.0.0,3.0.0
cli-boxes has different version: 3.0.0,2.2.1
type-fest has different version: 2.19.0,0.20.2,0.21.3,0.6.0
widest-line has different version: 4.0.1,3.1.0
bytes has different version: 3.0.0,3.1.2
@webassemblyjs/wasm-gen has different version: 1.11.5,1.11.1
registry-auth-token has different version: 3.3.2,4.2.2
registry-url has different version: 3.1.0,5.1.0
@webassemblyjs/helper-numbers has different version: 1.11.5,1.11.1
@webassemblyjs/helper-wasm-bytecode has different version: 1.11.5,1.11.1
estraverse has different version: 4.3.0,5.3.0
@webassemblyjs/helper-buffer has different version: 1.11.5,1.11.1
@webassemblyjs/helper-wasm-section has different version: 1.11.5,1.11.1
@webassemblyjs/wasm-opt has different version: 1.11.5,1.11.1
@webassemblyjs/wast-printer has different version: 1.11.5,1.11.1
@webassemblyjs/helper-api-error has different version: 1.11.5,1.11.1
@webassemblyjs/ieee754 has different version: 1.11.5,1.11.1
@webassemblyjs/leb128 has different version: 1.11.5,1.11.1
@webassemblyjs/utf8 has different version: 1.11.5,1.11.1
color-convert has different version: 1.9.3,2.0.1
d3-path has different version: 2.0.0,1.0.9
iconv-lite has different version: 0.4.24,0.6.3
d3-array has different version: 1.2.4,2.12.1
isarray has different version: 0.0.1,1.0.0
p-map has different version: 4.0.0,2.1.0
rbush has different version: 2.0.2,3.0.1
@antv/matrix-util has different version: 3.1.0-beta.3,3.0.4
@babel/helper-simple-access has different version: 7.20.2,7.22.5,7.21.5
emoji-regex has different version: 8.0.0,9.2.2
is-fullwidth-code-point has different version: 3.0.0,4.0.0
find-up has different version: 5.0.0,6.3.0,4.1.0,3.0.0
is-core-module has different version: 2.12.0,2.10.0
@vue/reactivity-transform has different version: 3.2.45,3.3.7
@babel/helper-annotate-as-pure has different version: 7.22.5,7.18.6
pkg-dir has different version: 7.0.0,3.0.0,4.2.0
@vue/compiler-core has different version: 3.2.45,3.3.7
@vue/runtime-core has different version: 3.2.45,3.3.7
@vue/compiler-ssr has different version: 3.2.45,3.3.7
magic-string has different version: 0.25.9,0.30.5
make-dir has different version: 3.1.0,2.1.0
dir-glob has different version: 2.2.2,3.0.1
ignore has different version: 3.3.10,5.2.0
pify has different version: 3.0.0,2.3.0,4.0.1
brace-expansion has different version: 1.1.11,2.0.1
path-key has different version: 3.1.1,2.0.1
shebang-command has different version: 2.0.0,1.2.0
@babel/helper-create-class-features-plugin has different version: 7.22.5,7.20.5
has-flag has different version: 4.0.0,3.0.0
mimic-fn has different version: 2.1.0,3.1.0
void-elements has different version: 3.1.0,2.0.1
constantinople has different version: 4.0.1,3.1.2
pug-attrs has different version: 3.0.0,2.0.4
pug-error has different version: 2.0.0,1.3.3
with has different version: 7.0.2,5.1.1
is-expression has different version: 4.0.0,3.0.0
token-stream has different version: 1.0.0,0.0.1
typedarray-to-buffer has different version: 1.0.4,3.1.5
bl has different version: 0.8.2,4.1.0
prr has different version: 0.0.0,1.0.1
bn.js has different version: 5.2.1,4.12.0
@jridgewell/sourcemap-codec has different version: 1.4.15,1.4.14
strip-bom has different version: 4.0.0,3.0.0
load-json-file has different version: 6.2.0,4.0.0
data-uri-to-buffer has different version: 4.0.1,2.0.2
@jest/expect-utils has different version: 29.5.0,29.7.0
jest-matcher-utils has different version: 29.5.0,29.7.0
@jest/transform has different version: 29.5.0,29.7.0
jest-haste-map has different version: 29.5.0,29.7.0
jest-regex-util has different version: 29.4.3,29.6.3
@types/yargs has different version: 17.0.12,16.0.5
slice-ansi has different version: 5.0.0,3.0.0,4.0.0
escape-string-regexp has different version: 1.0.5,5.0.0,2.0.0,4.0.0
@babel/helper-replace-supers has different version: 7.22.5,7.19.1
@babel/helper-optimise-call-expression has different version: 7.22.5,7.18.6
yallist has different version: 4.0.0,3.1.1
is-unicode-supported has different version: 1.3.0,0.1.0
ansi-regex has different version: 5.0.1,6.0.1,2.1.1,3.0.1
resolve-from has different version: 4.0.0,5.0.0
@webassemblyjs/floating-point-hex-parser has different version: 1.11.5,1.11.1
write-file-atomic has different version: 3.0.3,4.0.2,5.0.1
quickselect has different version: 1.1.1,2.0.0
object-keys has different version: 1.1.1,0.4.0,0.2.0
@vue/reactivity has different version: 3.2.45,3.3.7
locate-path has different version: 6.0.0,3.0.0,7.2.0,5.0.0
path-exists has different version: 4.0.0,5.0.0,3.0.0
pump has different version: 3.0.0,2.0.1
level-fix-range has different version: 1.0.2,2.0.0
shebang-regex has different version: 3.0.0,1.0.0
@babel/helper-member-expression-to-functions has different version: 7.22.5,7.18.9
type has different version: 1.2.0,2.7.2
strip-json-comments has different version: 3.1.1,2.0.1
is-plain-object has different version: 2.0.4,5.0.0
kind-of has different version: 6.0.3,3.2.2
is-arrayish has different version: 0.2.1,0.3.2
ini has different version: 1.3.8,2.0.0,3.0.1
p-locate has different version: 5.0.0,4.1.0,3.0.0,6.0.0
clone has different version: 0.1.19,1.0.4
yocto-queue has different version: 0.1.0,1.0.0
```

### PR DESCRIPTION
**Pull request by SoonIter**
## Summary

close #5477

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by chenjiahan** [comment]
@SoonIter can you resolve the conflicts and fix the CI~

**Comment by chenjiahan** [comment]
can you resolve the conflicts and CI again ❤️

**Comment by SoonIter** [comment]
> can you resolve the conflicts and CI again ❤️

sorry, i almost forgot it, delayed by phantom dependence problem and react multiple versions...

separate the bench case from dependency graph might be better, but it needs the refactor of benchmark

**Comment by chenjiahan** [comment]
> separate the bench case from dependency graph might be better

The bench case need to use `workspace:*` protocol to reference the local Rspack, so it may not be separated from the workspace.

Can this dependency issue be solved with a different approach?

**Comment by chenjiahan** [comment]
@SoonIter bump

**Review by chenjiahan — APPROVED** [review]

**Pull request merged**
