### PR TITLE
feat(rspack): NormalModuleReplacementPlugin

### PR DESCRIPTION
**Pull request by xc2**
## Summary

fixes:  #3522

thanks #6023

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
What about implement it in rust side and expose it to js side by builtin plugin, which has better performance

**Comment by ahabhgk** [comment]
I have an idea about this plugin, when the second argument is a string, builtin plugin will have better performance, when it is a function, js plugin (queried hook) will reduce the amount of rust <-> js call, so js plugin will have better performance. Since this is compatible with the PR's implementation, so let's merge this and we can implement the optimization in the future

**Review by ahabhgk — APPROVED** [review]
Thanks

**Comment by xc2** [comment]
> What about implement it in rust side and expose it to js side by builtin plugin, which has better performance

sry i just seen this. 

>  when it is a function, js plugin (queried hook) will reduce the amount of rust <-> js call,

yes I was wondering if it's worth creating a Rust implementation of this plugin, considering that it seems to be just a wrapper for nmf's xResolve hooks.

a replacement function is more common, and the webpack document of this plugin is also guiding one to modify `resource.request` and `createData.resource` instead of returning a new value.

**Pull request merged**
