### PR TITLE
perf(core): use prebundle to reduce dependencies

### PR DESCRIPTION
**Pull request by chenjiahan**
## Summary

Use prebundle to reduce dependencies of `@rspack/core` (12 deps -> 6 deps)

Screenshot 2024-05-07 at 14 16 11

How it works:

- Use [prebundle](https://github.com/rspack-contrib/prebundle) to bundle dependencies and output to the `compiled` folder.
- Use [tsc-alias](https://www.npmjs.com/package/tsc-alias) to alias the import path to the `compiled` folder.

resolve https://github.com/web-infra-dev/rspack/issues/5097

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by LingyuCoder — APPROVED** [review]

**Comment by chenjiahan** [comment]
!canary

**Comment by alfaproject** [comment]
How is this better? Now I have duplicate code in my node modules, ehhh

**Comment by chenjiahan** [comment]
Bundle dependency is a very practical optimization method, and we can see that projects like Next.js and Vite have adopted it.

- Next.js bundles dependencies and output to the `compiled` folder, just like Rspack does. see https://github.com/vercel/next.js/tree/canary/packages/next/src/compiled

- Vite bundles most of dependencies and outputs them as chunks, see: https://github.com/vitejs/vite/blob/main/packages/vite/rollup.config.ts#L65-L73

There are many benefits of bundle dependencies, including faster dependency installation and prevention of supply chain attacks caused by upgrades of indirect dependencies.

Regarding your concerns, while there may be duplicate code in node_modules, in most cases the code you need to download is less than before, because the bundling process removes unnecessary files.

**Comment by chenjiahan** [comment]
According to my calculations, this PR has reduced the install size by 800kB, and we can further optimize it.

**Pull request merged**
