### PR TITLE
perf: reduce memory consumption of `CachedSource`

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Summary

Syncing with rspack-sources https://github.com/web-infra-dev/rspack-sources/pull/144

## Checklist

- [ ] Tests updated (or **not required**).
- [ ] Documentation updated (or **not required**).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Review by SyMind — APPROVED** [review]

**Comment by h-a-n-a** [comment]
!bench

**Pull request merged**
