### PR TITLE
feat: add partial lazyOptions.backend options

### PR DESCRIPTION
**Pull request by tatchi**
## Summary

This adds partial types for `backend` property in `lazyCompilationOptions`. See https://github.com/web-infra-dev/rspack/issues/6717#issuecomment-2238854516

I haven't tested if it works, but according to https://github.com/web-infra-dev/rspack/issues/6717#issuecomment-2238823246 the options should be merged

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by JSerFeng — DISMISSED** [review]

**Comment by tatchi** [comment]
Any chance this could be release with `1.0.0-beta.0` ?

**Comment by chenjiahan** [comment]
CI failed, can you check it? @tatchi 

```
The following configs are implemented but not documented: experiments.lazyCompilation.backend, experiments.lazyCompilation.backend.client, experiments.lazyCompilation.backend.listen, experiments.lazyCompilation.backend.listen.port, experiments.lazyCompilation.backend.listen.host, experiments.lazyCompilation.backend.listen.backlog, experiments.lazyCompilation.backend.listen.path, experiments.lazyCompilation.backend.listen.exclusive, experiments.lazyCompilation.backend.listen.readableAll, experiments.lazyCompilation.backend.listen.writableAll, experiments.lazyCompilation.backend.listen.ipv6Only, experiments.lazyCompilation.backend.protocol
```

**Comment by tatchi** [comment]
I'm not sure what to do to fix CI failure 😅

**Comment by SoonIter** [comment]
> I'm not sure what to do to fix CI failure 😅. Where doc should be added ?

here,

website/docs/zh/config/experiments.mdx
website/docs/en/config/experiments.mdx

https://github.com/web-infra-dev/rspack/blob/06376fd845b6e3c6f45631b8331b620f414de1b7/website/docs/en/config/experiments.mdx#L95

https://github.com/web-infra-dev/rspack/blob/06376fd845b6e3c6f45631b8331b620f414de1b7/website/docs/zh/config/experiments.mdx#L101

**Review by JSerFeng — APPROVED** [review]

**Pull request merged**
