### PR TITLE
chore(diff): esm module

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Summary

Align `HarmonyExportExpressionDependency` and `HarmonyExportHeaderDependency ` with webpack. Then the codegen result of `export default` will be the same with webpack.

```js
// source
export default "aaa";

// before
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
var __WEBPACK_DEFAULT_EXPORT__ = "aaa";

// now, same as webpack
__webpack_exports__["default"] = "aaa"
```

## Test Plan

- Reuse `packages/rspack/tests/cases/parsing/harmony-xxx`

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #5290** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/5290?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #5300** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/5300?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/web-infra-dev/rspack/5290?utm_source=stack-comment).

**Comment by LingyuCoder** [comment]
!eco-ci

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!eco-ci

**Review by IWANABETHATGUY — APPROVED** [review]

**Pull request merged**
