### PR TITLE
Draft: add AMD dependencies

### PR DESCRIPTION
**Pull request by nilptr**
## Summary

add AMD dependencies for #4313.

- [AMDDefineDependency](https://github.com/webpack/webpack/blob/ff9e19809a42d2696e991dbca74391bf5d9d678d/lib/dependencies/AMDDefineDependency.js)
- [AMDRequireArrayDependency](https://github.com/webpack/webpack/blob/9943f3506a397a96e920c1a5bbd45815b05b7c67/lib/dependencies/AMDRequireArrayDependency.js)
- [AMDRequireContextDependency](https://github.com/webpack/webpack/blob/055737dc0ce38bacd10a8fbafedb137cfdd8a9f2/lib/dependencies/AMDRequireContextDependency.js)
- [AMDRequireDependency](https://github.com/webpack/webpack/blob/ca2fe13c8ae88d581b2c3ed7aae733efeb07d50c/lib/dependencies/AMDRequireDependency.js)
- [AMDRequireItemDependency](https://github.com/webpack/webpack/blob/3295f6c36f1407a4fbbd2ad1b35c315bd57409f1/lib/dependencies/AMDRequireItemDependency.js)

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by hardfist** [comment]
@nilptr you need review advice, please ping us

**Comment by SoonIter** [comment]
Hello, is this still in progress?

**Comment by GiveMe-A-Name** [comment]
@nilptr Do you need help ?

**Comment by nilptr** [comment]
hihi @GiveMe-A-Name sorry for late reply. I was busy with my job, didn't check github. Actually, I started a new branch, and this branch is discard. Let me close this PR and create a new one for review. 

Currently, I have finished the `AMDDefineDependencyParserPlugin` and `AMDRequireDependenciesBlockParserPlugin`, and added test cases for them. So far they seem to work well. But I still need more time (maybe 1or2 weeks) to do some integration. I will discuss the details with you guys this week. cc: @ahabhgk

Thank you.

**Pull request closed without merging**
