### PR TITLE
fix!: set default value of concatenateModules to true in production mode

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

Set optimization.concatenateModules to true in production mode by default

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!eco-ci

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by hardfist** [comment]
the performance regression seems huge

**Comment by h-a-n-a** [comment]
!bench

**Review by chenjiahan — APPROVED** [review]

**Pull request merged**
