### PR TITLE
feat(resolver): print detailed error messages for oxc_resolver (#4564)

### LINKED ISSUE #4564: feat(resolver): print detailed error messages for oxc_resolver
### System Info

None

### Details

The current implementation doesn't cover all error messages thrown by oxc_resolver:

https://github.com/web-infra-dev/rspack/blob/f3b27b9d7ad425ea97c06c35d088437558d022db/crates/rspack_core/src/resolver/resolver_impl.rs#L406-L433

Notice it only catches 2 errors and falls back to a generic error. oxc_resolver actually throws a lot more errors: https://github.com/web-infra-dev/oxc/blob/7d85492a03e34fec11e27eae42db28a7c3f12e16/crates/oxc_resolver/src/error.rs#L6

It would be nice to cover and print nice error messages for all of them.

### Reproduce link

_No response_

### Reproduce Steps

To get started, try Rspack with the `experiments.rspackFuture.new_resolver = true` configuration and then introduce any of the oxc_resolver errors in your setup.

### PR DESCRIPTION
**Pull request by msdlisper**
## Summary

I tied to fix  #4564

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by Boshen** [comment]
> [CLA assistant check](https://cla-assistant.io/web-infra-dev/rspack?pullRequest=4614) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/web-infra-dev/rspack?pullRequest=4614) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/web-infra-dev/rspack?pullRequest=4614) it.

@msdlisper Thank you, can you sign the CLA so I can approve this PR?

**Comment by msdlisper** [comment]
@Boshen I signed it

**Comment by msdlisper** [comment]
Hi~ @IWANABETHATGUY  Could you help me? This change of mine caused EnvironmentPlugin to fail testing. I have looked carefully to see if my change affected the collection of errors, but I still don't know for a while. This error occurs in both the Test Linux/Test Node pipeline

**Comment by msdlisper** [comment]
In the end, I found out that EnvironmentPlugin's test case specifically matched the no_path_found error and reported a more specific error message, so I chose to leave the logic as it was, which like this:
```
       {
          message: 'Failed to resolve hhh in /Users/zhangpeng/my/rspack/webpack-test/configCases/plugins/environment-plugin/index.js',
          formatted: 'error[internal]: Resolve error\n' +
            '   ┌─ configCases/plugins/environment-plugin/index.js:27:50\n' +
            '   │  \n' +
            '23 │       if (process.env.HHH !== "hhh") if (never) require("hhh");\n' +
            '24 │   });\n' +
            '25 │   \n' +
            '26 │   it("should import process.env var with empty value", () => {\n' +
            '27 │       if (process.env.III !== "") if (never) require("iii");\n' +
            '   │ ╭─────────────────────────────────────────────────────^\n' +
            '28 │ │ });\n' +
            '29 │ │ \n' +
            '   │ ╰^ Failed to resolve hhh in /Users/zhangpeng/my/rspack/webpack-test/configCases/plugins/environment-plugin/index.js\n' +
            '\n',
          title: 'Resolve error',
          compilerPath: 'iii'
        }
```
Although this error indicates the location is slightly off, it is much better than the following indication:
```
     {
          message: 'Path not found : /Users/zhangpeng/my/rspack/webpack-test/configCases/plugins/environment-plugin',
          formatted: 'error[internal]: Path not found : /Users/zhangpeng/my/rspack/webpack-test/configCases/plugins/environment-plugin\n' +
            '\n',
          title: '',
          compilerPath: 'iii'
        }
```

**Review by Boshen — APPROVED** [review]

**Pull request merged**
