### PR TITLE
feat: refresh overlay

### PR DESCRIPTION
**Pull request by JiangWeixian**
## Summary

Add overlay option support custom overlay or just use default overlay ui with `overlay: true`.

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
@JiangWeixian Still working on this one?

**Comment by JiangWeixian** [comment]
> @JiangWeixian Still working on this one?

yep, but blocked by other jobs, no time for further development. :(

**Comment by JiangWeixian** [comment]
@h-a-n-a cc

**Comment by h-a-n-a** [comment]
Would you please update the doc of the plugin?

**Comment by JiangWeixian** [comment]
> @JiangWeixian Would you please update the doc of the plugin?

where is the doc of this plugin... i can't find it...

**Review by h-a-n-a — APPROVED** [review]
Thank you!

**Comment by RainedX** [comment]
have some errors, I used: `client: {
      overlay: false
    },`
    but still have ovelay
image

**Pull request merged**
