### PR TITLE
feat: add nwjs target to rspack config

### PR DESCRIPTION
**Pull request by wxiaoyun**
## Summary

This PR addresses https://github.com/web-infra-dev/rspack/issues/3508
It seems that packages/rspack/src/config/target.js already handles the appropriate configs and the issue only requires me to modify zod schema 

## Checklist

- [x] Tests updated (or not required).
- [X] Documentation updated (or not required).

### CODE REVIEW

**Comment by wxiaoyun** [comment]
Time out on CI tests... Running pnpm run test:ci is passes locally 💩

**Comment by ahabhgk** [comment]
api needs update, run `pnpm api-extractor:local`

**Comment by ahabhgk** [comment]
And docs needs update

**Comment by h-a-n-a** [comment]
Please run `./x ae update` in the root directory. Snapshot doesn't suppose to have that much of the difference.

**Comment by ahabhgk** [comment]
Would you want to implement [`externalsPresets.nwjs`](https://arc.net/l/quote/qhthyoxw)?

**Comment by wxiaoyun** [comment]
> Would you want to implement [`externalsPresets.nwjs`](https://arc.net/l/quote/qhthyoxw)?

Is it something like `crates/rspack_plugin_externals/src/electron_target_plugin.rs`?

Lets chat over lark, xiaoyun.wu@bytedance.com

**Pull request merged**
