### PR TITLE
fix: should insert semi after import, export, debugger and class field

### PR DESCRIPTION
**Pull request by CPunisher**
## Checklist

ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion and [acorn](https://github.com/acornjs/acorn/blob/master/acorn/src/statement.js) (search `this.semicolon()`)

But I dont know how to construct the test case for ClassField

closes https://github.com/web-infra-dev/rspack/issues/7527

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
Would you please fix the CI?

**Comment by CPunisher** [comment]
> Would you please fix the CI?

There are ci errors on the main branch, where the latest commits also failed. ☹️

**Comment by h-a-n-a** [comment]
> > Would you please fix the CI?
> 
> There are ci errors on the main branch, where the latest commits also failed. ☹️

I see. Let's wait for a fix of the main branch then.

**Comment by JSerFeng** [comment]
let's see if #7534 fixes ci

**Comment by h-a-n-a** [comment]
> let's see if #7534 fixes ci

Looks like it did ;-)

**Review by h-a-n-a — APPROVED** [review]
Thank you

**Pull request merged**
