### PR TITLE
chore: copyFileSync to renameSync

### PR DESCRIPTION
**Pull request by PengBoUESTC**
## Summary

change copyFileSync to renameSync
## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [ ] New feature / Improvement
- [x] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hardfist** [comment]
can you explain why change `renameSync` to `copyFileSync`

**Comment by PengBoUESTC** [comment]
> can you explain why change `renameSync` to `copyFileSync`

change `copyFileSync` to `renameSync`,   `renameSync` means to move a file , `copyFileSync` will keep the origin files

**Comment by PengBoUESTC** [comment]
there may be some problems , the binding module should contain the `addons`  because of  that the `binding` file contains

`nativeBinding = require('./rspack.android-arm64.node')`

**Comment by hardfist** [comment]
we will keep copyFileSync since it doesn't cause problems

**Pull request closed without merging**
