### PR TITLE
refactor: remove extra CommonJs dependency locations

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary
Related to #7422 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
I found it necessary to introduce `SyntheticDependencyLocation` because some chunk files are generated virtually, which is beneficial for building information localization.

**Comment by shulaoda** [comment]
I will start governance again, and some dependencies can be directly addressed using `RealDependencyLocation`, as its location is actually determined. And in some places, we may need to use `SyntheticDependencyLocation` and `DependencyLocation`.

```rust
struct RealDependencyRange {
  pub end: u32,
  pub start: u32,
}

struct SyntheticDependencyName {
  pub end: u32,
  pub start: u32,
}

enum DependencyLocation {
  Real(RealDependencyRange),
  Synthetic(SyntheticDependencyName),
}

```

**Comment by shulaoda** [comment]
@h-a-n-a cc

**Comment by h-a-n-a** [comment]
> I will start governance again, and some dependencies can be directly addressed using `RealDependencyLocation`, as its location is actually determined. And in some places, we may need to use `SyntheticDependencyLocation` and `DependencyLocation`.
> 
> ```rust
> struct RealDependencyRange {
>   pub end: u32,
>   pub start: u32,
> }
> 
> struct SyntheticDependencyName {
>   pub name: String
> }
> 
> enum DependencyLocation {
>   Real(RealDependencyRange),
>   Synthetic(SyntheticDependencyName),
> }
> ```

Looks good. We might need `index` for `SyntheticDependencyName` as well in some places.

**Comment by h-a-n-a** [comment]
I changed the title to make it more specific.

**Review by h-a-n-a — COMMENTED** [review]
Thanks!

**Review by h-a-n-a — APPROVED** [review]

**Comment by shulaoda** [comment]
> Looks good. We might need `index` for `SyntheticDependencyName` as well in some places.

Yes, I will add `index` when necessary.

**Pull request merged**
