### PR TITLE
refactor: render manifest and hash hook

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

introduce `define_hook!` for customize the arguments (&T, &mut T, and arguments number, no more AsyncSeries2...) of the hook trait run fn

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!bench

**Review by JSerFeng — APPROVED** [review]

**Comment by ahabhgk** [comment]
!bench

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
