### PR TITLE
perf: source map

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

1. https://github.com/web-infra-dev/rspack-sources/pull/105
2. https://github.com/web-infra-dev/rspack-sources/pull/107
3. https://github.com/web-infra-dev/rspack-sources/pull/106
4. https://github.com/web-infra-dev/rspack-sources/pull/109
5. https://github.com/web-infra-dev/rspack-sources/pull/111
6. https://github.com/web-infra-dev/rspack-sources/pull/115
7. https://github.com/web-infra-dev/rspack-sources/pull/114

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
