### PR TITLE
revert: "fix: getHash occasionally panic when rebuild (#3970)"

### PR DESCRIPTION
**Pull request by h-a-n-a**
This reverts commit efa0dc68308de4626b593d892c352d71ea539e92.
For details: https://github.com/web-infra-dev/rspack/pull/4028

### CODE REVIEW

**Comment by hardfist** [comment]
can you add revert reason

**Comment by h-a-n-a** [comment]
> can you add revert reason

@hardfist see https://github.com/web-infra-dev/rspack/pull/4028

**Comment by ahabhgk** [comment]
Need rebase and fix CI

**Review by ahabhgk — APPROVED** [review]

**Comment by underfin** [comment]
!bench

**Pull request merged**
