### PR TITLE
refactor(typescript): refactor `packages/rspack/src/util` from js to ts and esm

### PR DESCRIPTION
**Pull request by jithyan**
## Summary

Addresses task refactor `packages/rspack/src/util` of issue:
https://github.com/web-infra-dev/rspack/issues/7225

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
Nice code, could you sign the CLA?

**Comment by jithyan** [comment]
> Nice code, could you sign the CLA?

@SoonIter I think my local commits were in my other account, maybe that's why the CLA signing didn't work? 
Anyway I did the changes as a new commit with the correct account, so it looks like it works now.

**Review by SoonIter — APPROVED** [review]

**Comment by SoonIter** [comment]
> I think my local commits were in my other account, maybe that's why the CLA signing didn't work? Anyway I did the changes as a new commit with the correct account, so it looks like it works now.

Yeah, you are right, it looks nice now, I'll merge it

**Comment by SoonIter** [comment]
thanks 🫶🏻

**Pull request merged**
