### PR TITLE
docs: fix banner link

### PR DESCRIPTION
**Pull request by Sunny-117**
## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
Thanks!

**Comment by chenjiahan** [comment]
@Timeless0911 Rspress should apply i18n for banner links in this case

**Comment by Timeless0911** [comment]
> @Timeless0911 Rspress should apply i18n for banner links in this case

https://github.com/web-infra-dev/rspress/issues/924  already have issue tracking it.

**Comment by chenjiahan** [comment]
👍

**Pull request merged**
