### PR TITLE
feat: add finishModules hook

### PR DESCRIPTION
**Pull request by tuchg**
## Related issue (if exists)
*  #2229

## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [x] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [x] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by ahabhgk — APPROVED** [review]
LGTM, thank you!

**Comment by faga295** [comment]
image
Is this error cause by this pr?

**Comment by ahabhgk** [comment]
There shouldn't be an error, have you run `pnpm build:binding:debug` or `pnpm build:binding:release`.

**Comment by faga295** [comment]
I've just realized this, it's stupid.

**Pull request merged**
