### PR TITLE
fix: perf degradation in devtool plugin

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

Fix perf degradation in #8136

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by SyMind** [comment]
!bench

**Review by h-a-n-a — APPROVED** [review]

**Comment by chenjiahan** [comment]
How was this perf degradation discovered?

**Comment by SyMind** [comment]
@chenjiahan The following code caused performance degradation:

```rust
raw_assets
     .into_par_iter()
     .map(|(file, asset)| async {
        // do something
    });
```

The above code uses the `into_par_iter` method, expecting to leverage `Rayon` for concurrent iteration. However, the closure passed to `map` won't execute the synchronous code concurrently because the synchronous code is wrapped within an `async` block. The `async` block is an anonymous structure that implements the `Future` trait and the closure simply returns this structure.

Rayon only handles the creation of these Future trait instances concurrently.

**Comment by chenjiahan** [comment]
Get 👍

**Comment by Narretz** [comment]
Can someone explain how the benchmark works? Because I see "current" here, and it has +% almost everywhere. Doesn't it mean the change is slower than before?

**Comment by SyMind** [comment]
@Narretz The benchmark differs from https://github.com/web-infra-dev/rspack/commit/4ea491e84c77d42917422844b0e2ca72a73bb265.

Within this range, there is a specific performance degradation caused by rolling back a particular algorithm in rspack-sources. However, after rolling back the code, I found that the degradation was greater than expected, with a maximum degradation of 6.83%.

I reviewed other commits and discovered another unexpected degradation. This commit is intended to fix that, and then the degradation of this benchmark is as expected.

**Pull request merged**
