### PR TITLE
style: use inlined args for `format!`

### LINKED ISSUE #8227: Some `panic` and other statements can be simplified
We can improve readability by replacing lines like

```rust
panic!(
  "expected a module ordinal for identifier '{}', but none was found.",
  module
)
```

with

```rust
panic!("expected a module ordinal for identifier '{module}', but none was found.")
```

This should improve the codebase's maintainability and developer productivity.

### PR DESCRIPTION
**Pull request by hamirmahal**
## Summary

Fixes #8227

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
This pull request shouldn't cause any user-facing changes.

The goal here is to improve the codebase's maintainability and developer productivity.

**Comment by h-a-n-a** [comment]
Style changes would be better with clippy rule changes. Would you please see if there's any rule can help us avoid regressions?

**Comment by hamirmahal** [comment]
Sure!

**Comment by h-a-n-a** [comment]
Would you mind me editing your PR to get it merged?

**Review by h-a-n-a — DISMISSED** [review]
Thank you!

**Comment by hamirmahal** [comment]
You're welcome! Would you happen to know why https://github.com/web-infra-dev/rspack/actions/runs/12369367778/job/34524631512?pr=8228 is failing?

**Comment by LingyuCoder** [comment]
> You're welcome! Would you happen to know why [web-infra-dev/rspack/actions/runs/12369367778/job/34524631512?pr=8228](https://github.com/web-infra-dev/rspack/actions/runs/12369367778/job/34524631512?pr=8228) is failing?

We changed the rules of some workflows. So need to rebase the branch.

**Review by LingyuCoder — APPROVED** [review]

**Pull request merged**
