### PR TITLE
feat: support `ReactFlight`

### PR DESCRIPTION
**Pull request by hyf0**
## Related issue (if exists)

See #3051 

## Summary

Test repo https://github.com/hyf0/server-components-demo-on-rspack

<details open=true>
  <summary><h2>Walkthrough</h2></summary>

</details>

### CODE REVIEW

**Comment by hyf0** [comment]
!canary

**Comment by hyf0** [comment]
!canary

**Comment by hyf0** [comment]
!canary

**Comment by hardfist** [comment]
close for stale

**Pull request closed without merging**
