### PR TITLE
chore: bump swc to 0.76.48

### PR DESCRIPTION
**Pull request by h-a-n-a**

### CODE REVIEW

**Comment by hyf0** [comment]
Is this update just a routine for swc or trying to fix some bugs?

**Comment by h-a-n-a** [comment]
> Is this update just a routine for swc or trying to fix some bugs?

It is intended to fix a resolving issue from @underfin, but it's yet to be confirmed. You may regard it as a routine upgrade.

**Comment by hardfist** [comment]
we need a rule for upgrade routine swc since it's risky

**Comment by hyf0** [comment]
Any update?

**Pull request closed without merging**
