### PR TITLE
feat: support stage for processAssets

### PR DESCRIPTION
**Pull request by ahabhgk**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
