### PR TITLE
perf: add cache for source map

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

Implement a memory cache within the `SourceMapDevToolPlugin` to eliminate redundant Source Map calculations for identical sources during the **HMR** phase.

In an actual project emitting over 200 assets, source map calculation times have been improved with caching implemented within the `SourceMapDevToolPlugin`.

Without cache: Saving a file—whether modified or unmodified—previously required over 20 seconds for source map generation.

image

With cache:

* Saving an unmodified file now takes approximately 700ms.

image

* Saving a modified file allows for targeted recalculations, lowering the source map generation time to about 4.5 seconds for the affected file.

image

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Review by jerrykingxyz — APPROVED** [review]

**Pull request merged**
