### PR TITLE
feat: another export case is unexpectedly warning

### PR DESCRIPTION
**Pull request by Lantianyou**
## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hyf0** [comment]
Thanks for your contribution. Could you add more context to the summary?

**Comment by IWANABETHATGUY** [comment]
Only adding a test case does not make much sense, I prefer open this as an issue. https://github.com/web-infra-dev/rspack/issues/2521. Since you already open an issue, I will try to fix it as soon as possible.

**Comment by Lantianyou** [comment]
Thanks, I opened this PR accidentally, feel free to close.

**Comment by IWANABETHATGUY** [comment]
> Thanks, I opened this PR accidentally, feel free to close.

Thanks for your contribution, this issue is not new contributor friendly, that's why I am gonna take over it, if you are interested in this feel free to take it.

**Pull request closed without merging**
