### PR TITLE
perf(rspack): use `cow-utils` instead

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary

Related to https://github.com/oxc-project/oxc/issues/5586

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
!benchmark

**Comment by shulaoda** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Review by h-a-n-a — APPROVED** [review]

**Comment by h-a-n-a** [comment]
Thanks!

**Pull request merged**
