### PR TITLE
chore: modify diff plugin options

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!canary

**Review by jerrykingxyz — APPROVED** [review]

**Pull request merged**
