### PR TITLE
chore: optimize diff test case

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Summary

1. Modify diff cases
  - Remove react refresh plugin
  - Use prod mode
  - Use experiments css 
2. Transform generated code of diff case to prevent unnecessary diff lines
  - Add `ignoreBlockOnlyStatement` to prevent differences caused by single-statement blocks
  - Add `ignoreSwcHelpersPath` to prevent differences caused by injecting @swc/helpers
  - Add `ignoreObjectPropertySequence` to prevent differences caused by sequence of object properties
  - Add `ignoreCssFilePath` to prevent differences caused by webpack css local idents

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Review by hardfist — APPROVED** [review]

**Pull request merged**
