### PR TITLE
chore: add comparator for diff tester

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Summary

Re-implement #5002 

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!canary

**Comment by LingyuCoder** [comment]
!canary

**Review by jerrykingxyz — APPROVED** [review]

**Pull request merged**
