### PR TITLE
feat(core)!: bump swc_core to 9.0.0

### PR DESCRIPTION
**Pull request by andersk**
## Summary

swc_core 8 has breaking changes to the WASM interface for SWC plugins (swc-project/swc#9771), so we need to upgrade in order to use current SWC plugins.

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by chenjiahan** [comment]
Thanks!

According to the Rspack version strategy, SWC's breaking changes will be included in the next Rspack minor version.

And we plan to release Rspack v1.2.0 this month. Rspack v1.2.0-alpha.0 should be released next week.

**Comment by chenjiahan** [comment]
We plan to release Rspack 1.2.0 alpha.0 next week. @andersk can you resolve the conflicts so that we can merge this PR? ❤️

**Comment by andersk** [comment]
@chenjiahan Done, and bumped to 9.0.0.

**Review by chenjiahan — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by chenjiahan** [comment]
!bench

**Pull request merged**
