### PR TITLE
feat: Disable source maps for rspack core

### PR DESCRIPTION
**Pull request by RussellCanfield**
## Summary

Disable source maps for rspack/core - #3515. Change is limited to rspack/core, the new tsconfig.lib.config file will only be used on builds which is what the github action triggers. I wasn't sure if we wanted to rimraf the dist folder, similar to rspack/cli, it should be harmless if we want to add it.

## Test Plan

Execute pnpm build:js, or build the rspack/core project directly. Ensure the "dist" folder is deleted prior to running build. Ensure the "dist" folder contains no .map files after the build.

### CODE REVIEW

**Comment by hyf0** [comment]
Thanks for your contribution. May I ask why we need to disable the source map of `@rspack/core`?

**Comment by hardfist** [comment]
can you help fix all package？

**Comment by hardfist** [comment]
> Thanks for your contribution. May I ask why we need to disable the source map of `@rspack/core`?

see related issue for more context

**Review by hyf0 — APPROVED** [review]

**Comment by RussellCanfield** [comment]
> can you help fix all package？

I can do that, let me do them in separate PRs, I will reference the same issue for context.

**Review by hardfist — APPROVED** [review]

**Pull request merged**
