### PR TITLE
chore: support import.meta.webpack

### PR DESCRIPTION
**Pull request by woai3c**
## Summary
* support `import.meta.webpack`
* `import.meta.env` `import.meta.env.xxx` shoud return `false`

## Checklist

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by SyMind** [comment]
Close https://github.com/web-infra-dev/rspack/issues/4350

**Comment by SyMind** [comment]
@woai3c Would you like to continue to make this test case fully pass? webpack-test/cases/esm/import-meta

**Comment by woai3c** [comment]
> @woai3c Would you like to continue to make this test case fully pass? webpack-test/cases/esm/import-meta

Thank you for reviewing the code. I will try to pass all the tests.

**Comment by LingyuCoder** [comment]
You may also need to handle `typeof`, `evaluateTypeof` and `evaluateIdentifier`. The implementation in webpack can be found [here](https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportMetaPlugin.js#L195-L212). The rspack example can be found [here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs#L283-L330). This is very useful for evaluation optimization.

**Comment by woai3c** [comment]
> You may also handle `typeof`, `evaluateTypeof` and `evaluateIdentifier`. The implementation in webpack can be found [here](https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportMetaPlugin.js#L195-L212). The rspack example can be found [here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs#L283-L330). This is very useful for evaluation optimization.

Thank you for your suggestion, and I also encountered a difficult problem. Do you have any suggestions for this test? At present, there is no idea, it seems that we need to start with the AST of the entire sentence.
```js
it("should support destructuring assignment", () => {
	let version, url2, c;
	({ webpack: version } = { url: url2 } = { c } = import.meta);
	expect(version).toBeTypeOf("number");
	expect(url2).toBe(url);
	expect(c).toBe(undefined);
});
```

**Comment by LingyuCoder** [comment]
> ```js
> import.meta
> ```

Seems to relate to the parser plugin([here](https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js#L1706-L1708)), need to save the properties while walking the ast. You can try to add this in rspack([here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs)). Use pre walk to parse the deconstruct properties and get it in `import_meta_plugin`

**Comment by woai3c** [comment]
> > > You may also handle `typeof`, `evaluateTypeof` and `evaluateIdentifier`. The implementation in webpack can be found [here](https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportMetaPlugin.js#L195-L212). The rspack example can be found [here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs#L283-L330). This is very useful for evaluation optimization.
> > 
> > 
> > Thank you for your suggestion, and I also encountered a difficult problem. Do you have any suggestions for this test? At present, there is no idea, it seems that we need to start with the AST of the entire sentence.
> > ```js
> > it("should support destructuring assignment", () => {
> > 	let version, url2, c;
> > 	({ webpack: version } = { url: url2 } = { c } = import.meta);
> > 	expect(version).toBeTypeOf("number");
> > 	expect(url2).toBe(url);
> > 	expect(c).toBe(undefined);
> > });
> > ```
> 
> Seems to relate to the parser plugin([here](https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js#L1706-L1708)), need to save the properties while walking the ast. You can try to add this in rspack([here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs)). Use pre walk to parse the deconstruct properties and get it in `import_meta_plugin`

Ok, got it!

**Pull request closed without merging**
