### PR TITLE
revert: apply entry and externals eagerly

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

eagerly apply entry and externals is a break change, so revert it before we release a patch version

## Test Plan
- eco-ci should pass

### CODE REVIEW

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
Hmmm, what's the exact breaking change then? I didn't fully understand it from your description.

**Comment by underfin** [comment]
!bench

**Comment by ahabhgk** [comment]
!eco-ci

**Review by 9aoy — APPROVED** [review]

**Pull request merged**
