### PR TITLE
feat: support function type for `splitChunks.{cacheGroup}.{test, name}`

### LINKED ISSUE #4376: function type support missing for critical splitChunks options
### System Info

N/A

### Details

Hello, 
with rspack we are currently missing the support of function type for the below critical options.

1) splitChunks.cacheGroups.{cacheGroup}.test: https://www.rspack.dev/config/optimization-split-chunks.html#splitchunkscachegroupscachegrouptest
2) splitChunks.cacheGroups.{cacheGroup}.name :  https://www.rspack.dev/config/optimization-split-chunks.html#splitchunkscachegroupscachegroupname

Both of these options are supported as function types in webpack which makes it possible to parse modules at build time. 
https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouptest

### Reproduce link

_No response_

### Reproduce Steps

N/A

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #4376 

Support the function type for `optimize.splitChunks.{cacheGroup}.{name, test}`

NOTE: This is an initial implementation and I do **not** guarantee that it will function correctly in all cases. If there are any questions or issues, please raise the corresponding issue.

### CODE REVIEW

**Comment by JSerFeng** [comment]
!bench

**Review by JSerFeng — APPROVED** [review]

**Comment by pushkargupta9807** [comment]
hello @bvanjoi - can we also add the function type or regexp for splitChunks.{cacheGroup}. chunks  ? like below in webpack 
https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks

Thanks!

**Comment by bvanjoi** [comment]
@pushkargupta9807 it would be better to open a new issue for this matter which will facilitate us in keeping track of this.

**Comment by pushkargupta9807** [comment]
@bvanjoi which respack version is the above fix available to try out ?

Also as per your suggestion, I submitted a new issue : https://github.com/web-infra-dev/rspack/issues/5188 

Thanks!

**Pull request merged**
