### PR TITLE
chore: remove unused vars & prefer const & remove default generic value

### PR DESCRIPTION
**Pull request by SnowingFox**
## Summary

- Remove some unused vars
- Prefer const which is not reassigned
- Remove generic which has the same default type value

image

### CODE REVIEW

**Comment by hyf0** [comment]
You might need to squash you commits and exclude the commit of `liumengjie.react`, so the CLA check could be passed.

**Comment by SnowingFox** [comment]
The ci is really weird

**Comment by hardfist** [comment]
@SnowingFox are you willing to fix the conflict and we will review it ASAP

**Comment by SnowingFox** [comment]
> @SnowingFox are you willing to fix the conflict and we will review it ASAP

done

**Review by hardfist — APPROVED** [review]

**Comment by hardfist** [comment]
@SnowingFox  thanks!

**Pull request merged**
