### PR TITLE
chore: use `zx` to replace xtask

### PR DESCRIPTION
**Pull request by hyf0**
### <samp>🤖 Generated by Copilot at 5abf645</samp>

This pull request removes the xtask crate and replaces its functionality with node scripts for benchmarking the rspack crate with different versions of the three.js library. It also updates the code owners file, the TypeScript config file, and the cargo config file to reflect the changes. Additionally, it adds a utility script to check the workspace root and a typecheck script to verify the scripts folder.

<details open=true>
  <summary><h2>Walkthrough</h2></summary>

### <samp>🤖 Generated by Copilot at 5abf645</samp>

*  Remove `xtask` crate and replace its commands with node scripts for benchmarking ([link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-9a4f3e4537ebb7474452d131b0d969d89a51286f4269aac5ef268e712be17268L8-R8), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L5-R5), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-89ef11f0a86d66a23c336004fbf4c46d6eb506ef55fa05833874c668dc19cf23L31-R38), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-89ef11f0a86d66a23c336004fbf4c46d6eb506ef55fa05833874c668dc19cf23L46-R58), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-b8b7d3cbf1a9a81e7957deb2a7fb9dd86d6a165547f9ddf9689a2c7f19244031R1-R26), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-deab30c4784cf2f3ef390532a9a4d7f5d56f04367c5f3ca9fd4494a98258faf8R1-R48), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-4bb4bf59603c1020893a63713d4de768d10e311991ffa1d6b5868b6be4dbae74), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-de5421079a1d7542bf0936875e6b6af5eb68ea42b805d370224a3cf5d40f87f5), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-9c5e61698d6d8a8ef4a3da7075c31857769134a932ac141d4eb62f68f131aa35))
* Refactor code owners specification to use cargo config feature ([link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L2-R29), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R74))
* Add utility and type checking scripts for node scripts ([link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-4acaffa5ee9975a029d63ccec59006b54a264823dfff7dd023feb797a5388f2cR1-R25), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-d1c07ffe5136d76ccdbe2e1007fce4924304c53acf7aba2bce15ed9d2df63aeeL3), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-d1c07ffe5136d76ccdbe2e1007fce4924304c53acf7aba2bce15ed9d2df63aeeL16-R15), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-d74f97384f03053c517e34bcd695eefd751944cd55183d693ae99ef3bc50d016L6-R12))
* Improve TypeScript compiler options for scripts ([link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-bb0ef161f0c803b8b038faab449fbbec5024e7e85760cf4e6a6d9179f7e4c0eaL6-R6), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-bb0ef161f0c803b8b038faab449fbbec5024e7e85760cf4e6a6d9179f7e4c0eaL35-R35), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-bb0ef161f0c803b8b038faab449fbbec5024e7e85760cf4e6a6d9179f7e4c0eaL58-R58), [link](https://github.com/web-infra-dev/rspack/pull/2840/files?diff=unified&w=0#diff-bb0ef161f0c803b8b038faab449fbbec5024e7e85760cf4e6a6d9179f7e4c0eaL94-R94))

</details>

### CODE REVIEW

**Comment by hyf0** [comment]
!bench

**Comment by hyf0** [comment]
!bench

**Comment by hyf0** [comment]
@IWANABETHATGUY The benchmark CI runs successfully. You are free to review this PR.

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY The benchmark CI runs successfully. You are free to review this PR.

Are you sure ? baseline now is 861 times slower than current branch

**Review by IWANABETHATGUY — APPROVED** [review]

**Pull request merged**
