### PR TITLE
release: 0.4.0

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Breaking changes
- [x] [Breaking change: moving builtins options to builtin plugins](https://github.com/web-infra-dev/rspack/pull/4012)
- [x] Deprecating default react refresh
- [x] [Breaking change: Deprecating default transformation](https://github.com/web-infra-dev/rspack/discussions/4070)
- [x] Deprecating builtin:sass-loader
- [x] https://github.com/web-infra-dev/rspack/pull/4245
- [x] make @rspack/core as peerDep https://github.com/web-infra-dev/rspack/issues/4644 @hardfist 

## New defaults
- [x] Use `optimization.moduleIds` deterministic 
- [x] deprecate devFriendlySplitChunks and experiments.newSplitChunks #4580 
- [x] enable newResolver by default @Boshen #4656

## LTS change
- [X] Drop Node 14 support https://github.com/web-infra-dev/rspack/issues/4583

### CODE REVIEW

**Comment by hyf0** [comment]
I would like to remove `experiments.newSplitChunks` option since #3120 is resolved in `0.4.0`. There's no need to maintain the old `SplitChunksPlugin` code anymore.

**Comment by h-a-n-a** [comment]
FYI, GitHub's rebase with empty commit seems buggy, it will close the PR right away. So please update this PR with merge.

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
MODERN_REF=rspack-0.4.0 !eco-ci modern

**Comment by h-a-n-a** [comment]
MODERN_REF=rspack-0.4.0 !eco-ci modernjs

**Comment by h-a-n-a** [comment]
MODERN_REF=update-rspack-0-4 !eco-ci modernjs

**Comment by hardfist** [comment]
!canary

**Comment by hardfist** [comment]
the lock conflict is caused by we switch pnpm@8

**Comment by hardfist** [comment]
!canary

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
!canary

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
!canary

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
!canary

**Comment by hardfist** [comment]
!eco-ci

**Review by ahabhgk — DISMISSED** [review]

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
