### PR TITLE
chore: port mini-css-extract tests

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

- Port tests from `mini-css-extract-webpack-plugin`
- Fix bug in importModule, which can block the thread

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by JSerFeng** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/5220?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #4835** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/4835?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #4785** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/4785?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #4718** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/4718?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #5072** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/5072?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #5220** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/5220?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/web-infra-dev/rspack/5220?utm_source=stack-comment).

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
