### PR TITLE
feat: support `size` option for optimization.chunkIds config

### LINKED ISSUE #8605: [Feature]: Configuration optimization.chunkIds support "size"
### What problem does this feature solve?

The config optimization.chunkIds is not support "size".

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/optimization/#optimizationchunkids

### PR DESCRIPTION
**Pull request by inottn**
## Summary
close #8605

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by inottn** [comment]
There are multiple formats in this document, and I think they could be unified into one. However, I'm not sure which format would be the most appropriate.

https://github.com/web-infra-dev/rspack/blob/8646ecf26004a5c99ff09cab2b49e457d5d9ca09/website/docs/en/config/optimization.mdx?plain=1#L25-L29

https://github.com/web-infra-dev/rspack/blob/8646ecf26004a5c99ff09cab2b49e457d5d9ca09/website/docs/en/config/optimization.mdx?plain=1#L55-L58

https://github.com/web-infra-dev/rspack/blob/8646ecf26004a5c99ff09cab2b49e457d5d9ca09/website/docs/en/config/optimization.mdx?plain=1#L371-L376

**Comment by chenjiahan** [comment]
@LingyuCoder @ahabhgk cc~

**Review by ahabhgk — APPROVED** [review]
LGTM, thanks!

**Comment by ahabhgk** [comment]
`'deterministic'`
`'named'`
`true`
`false`

I prefer this format

**Comment by chenjiahan** [comment]
I think most of these differences come from translation tools, their original intentions are similar. You can choose the more detailed version.

**Comment by inottn** [comment]
> I think most of these differences come from translation tools, their original intentions are similar. You can choose the more detailed version.

I wasn't clear enough in my expression. What I actually meant was the format of this area. 😄

image

**Pull request merged**
