### PR TITLE
fix: some js hooks are always enabled

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

We forgot some hooks when check disabling

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by jerrykingxyz** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by hardfist** [comment]
this happens again

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Review by jerrykingxyz — APPROVED** [review]

**Pull request merged**
