### PR TITLE
feat: progress plugin

### PR DESCRIPTION
**Pull request by faga295**
## Summary
#4973 

Last time in #3803, we only supported the activeModule report and progress_handler compatibility. However, it had some issues, such as the default_handler not correctly reflecting the build duration. Due to several missing sealing hooks, the process duration wasn't accurate either.

Comparing to webpack, rspack will build modules with mulitple threads, between `build_module` and `succeed_module` , maybe other module will be build in other thread. Now we have `default_handler` and `progress_handler`, and in the future there may be some custom handler from user.
We don't want the progress bar shows "building module2" after module2 build succeed, so we should correct the progress bar message, when module2 `succeed_module`. In code side, I use `linked_hash_map` which can keep the insertion order to record the active modules, so after module2 build succeed, we can get the last active module accroding to the insertion order(I'm not sure whether there has performance problem)
image
In profile mode, this mode will print module build message in terminal, we should guarantee module's build time instead of module's build order
image

image

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by faga295** [comment]
@ahabhgk  @hardfist  I've encountered an issue, which can be described as follows: Due to rspack using multiple threads for building modules, it means that during the build process of one module, other modules may complete their builds. Since the profile report's time is calculated by subtracting the time of the last handler trigger from the time of the current handler trigger, both succeed_module and build_module will trigger the handler. Through these two hooks, the module's build time can be obtained. However, if other modules trigger succeed_module in the middle, the accuracy of the module's build time may be compromised. I'm not quite sure how to achieve the best compatibility with webpack plugins and ensure the accuracy of module build times. Therefore, I wanted to ask if you have any recommended solutions or best practices for this situation.

**Comment by ahabhgk** [comment]
I suggest update the progress at make start and make end, missing the each module's progress is acceptable.

The progress of seal phase should be more accurate

**Comment by faga295** [comment]
I added a time parameter to `default_handler`. If this parameter `is_some`, the report time will use this time.The `self.active_modules` will store the build start time.The `succeed_module` will use the build start time to get the real build time and finaly pass the time to `handler`.

**Comment by ahabhgk** [comment]
!bench

**Review by ahabhgk — APPROVED** [review]
Thanks

**Pull request merged**
