### PR TITLE
feat: support asset info source filename

### PR DESCRIPTION
**Pull request by faga295**
#3851

### CODE REVIEW

**Comment by underfin** [comment]
The `packages/rspack/tests/fixtures/icon.png` is so large, you use an empty png to test.

**Comment by faga295** [comment]
@underfin cc

**Comment by ahabhgk** [comment]
Looks great, but CI need pass, you can run `pnpm run test -- -u` under `packages/rspack` to update the snapshot

**Review by ahabhgk — APPROVED** [review]
Thanks!

**Pull request merged**
