### PR TITLE
chore: add rust rebuild test function feature

### PR DESCRIPTION
**Pull request by suxin2017**
### <samp>🤖 Generated by Copilot at 50a05bb</samp>

This pull request adds a new function `test_hmr_fixture` to the `rspack_testing` crate, which tests the hot module reloading (HMR) feature of the `rspack` tool. It also updates and adds some examples to demonstrate and compare the HMR feature with the normal build feature. The examples use hard-coded fixture paths and console log statements.

<details open=true>
  <summary><h2>Walkthrough</h2></summary>

### <samp>🤖 Generated by Copilot at 50a05bb</samp>

*  Add a new function `test_hmr_fixture` to the `rspack_testing` crate that tests the hot module replacement (HMR) feature of the compiler for a given fixture ([link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-01db654b3c7e1c7713353ef9e336f8d7aa7e885cf75d902efed9168ffcf1c2c4L5-R5), [link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-a17804366fb795a1395f00e4406072e66850b85ad20d2c583480456734c517b4R1), [link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-a17804366fb795a1395f00e4406072e66850b85ad20d2c583480456734c517b4R65-R148))
*  Add two examples of how to use the `test_hmr_fixture` function in the `test-cli.rs` and `test-hmr-cli.rs` files ([link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-cbe6300ee9b25db1b54c929bb574e8252329cc773ef6b30f6a6d019377ab6ef1L5-R8), [link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-cbe6300ee9b25db1b54c929bb574e8252329cc773ef6b30f6a6d019377ab6ef1L16-R15), [link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-4ebf25678023edcf60be53f775fd3c4056d88854104b5b4b09baebb19ec0286dR1-R18))
*  Add a new `test.config.json` file to the `simple` example to provide some configuration options for the testing framework or the compiler ([link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-5e95d771ecdb6a7221748fd344783dde8944c786b0dbf1ea8cac6662008328b5L1-R1))
*  Add some console log statements to the `index.js` file in the `simple` example to demonstrate or debug the HMR feature or the module caching behavior ([link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-fb04091c0c1d38db8d0d6709dd6a8773706a75a6115818a86cd5b013ac164c6dR1), [link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-b6655ad5c62f15237a82cc6f1c140d2d6ccff6861d25dc2f1e4771a8bee5f2b2L1-R1))
*  Add the expected output of the compiler for the `simple` example in the `main.js` file ([link](https://github.com/web-infra-dev/rspack/pull/3091/files?diff=unified&w=0#diff-f60c29e0b5d0bd0e75426ad2f6f931f4dab589c1bd10d100e6f4d1fe72df38c8L1-R11))

</details>

### CODE REVIEW

**Comment by suxin2017** [comment]
Do we need hot update tests for rust, because I don't know how to do hot update tests in rust because of the lack of this tool

@ahabhgk @h-a-n-a

**Comment by ahabhgk** [comment]
I don't suggest add hmr test at rust side, hmr can't works without `@rspack/dev-server`, which is written in js, so normally we test hmr at js side.

**Comment by suxin2017** [comment]
> I don't suggest add hmr test at rust side, hmr can't works without `@rspack/dev-server`, which is written in js, so normally we test hmr at js side.

Maybe there is something wrong with the description of my proposal. I want to add the test method of rebuild to the rust layer, through the changed and removed files, to facilitate testing possible problems in the rebuild process

**Comment by ahabhgk** [comment]
IMO test at rust side enable better debug experience, so rebuild test at rust side is nice to have, you can checkout `packages/rspack/tests/WatchTestCases.test.ts` for reference, it's written in js but the main idea is using `writeFile` to trigger the rebuild, I think we can do the same in rust side.

**Comment by suxin2017** [comment]
> IMO test at rust side enable better debug experience, so rebuild test at rust side is nice to have, you can checkout `packages/rspack/tests/WatchTestCases.test.ts` for reference, it's written in js but the main idea is using `writeFile` to trigger the rebuild, I think we can do the same in rust side.

So it makes sense, right? So I'm going to follow up

**Review by hyf0 — APPROVED** [review]

**Comment by hyf0** [comment]
Thank you!

**Pull request merged**
