### PR TITLE
fix(rspack_core): fix resolver returning broken missing dependencies

### PR DESCRIPTION
**Pull request by Boshen**
closes https://github.com/web-infra-dev/modern.js/issues/5227

See https://github.com/oxc-project/oxc_resolver/pull/54 for details

### CODE REVIEW

**Comment by Boshen** [comment]
!canary

**Comment by Boshen** [comment]
!canary

**Comment by Boshen** [comment]
!canary

**Comment by Boshen** [comment]
!canary

**Comment by Boshen** [comment]
!eco-ci

**Comment by Boshen** [comment]
!eco-ci

**Comment by Boshen** [comment]
It seems like the broken test cases aren't related to this PR.

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
