### PR TITLE
refactor: use `realDependencyLocation` instead of `range` in dependency

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary

Related to #7422 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
I introduced `DependencyRange` because some dependencies's `span` are only used as `range` and don't require `to_loc`. This approach reduces memory usage since `RealDependencyLocation` has an additional `source: Option<Arc<dyn SourceLocation>>`.

_Originally posted by @shulaoda in https://github.com/web-infra-dev/rspack/issues/7871#issuecomment-2345210104_

**Comment by LingyuCoder** [comment]
LGTM, cc @h-a-n-a

**Review by LingyuCoder — APPROVED** [review]

**Comment by h-a-n-a** [comment]
Do you have other purpose of introducing this data structure other than its size?

**Comment by shulaoda** [comment]
> Do you have other purpose of introducing this data structure other than its size?

Perhaps it can be used as a substitute for `ErrorSpan`?

**Comment by h-a-n-a** [comment]
> > Do you have other purpose of introducing this data structure other than its size?
> 
> Perhaps it can be used as a substitute for `ErrorSpan`?

That's the question I was wondering. If we have `ErrorSpan`, why bother creating another `DependencyRange`? I'm still thinking about to unify these locations and ranges into `RealDependencyLocation`.

**Comment by shulaoda** [comment]
> That's the question I was wondering. If we have `ErrorSpan`, why bother creating another `DependencyRange`? I'm still thinking about to unify these locations and ranges into `RealDependencyLocation`.

If an additional `usize` memory overhead is acceptable, we can do it this way. Alternatively, we could place the `Sourcemap` into the `Dependency` and use `range.to_loc(self.sourcemap)` for location transformation.

**Comment by h-a-n-a** [comment]
> If an additional `usize` memory overhead is acceptable, we can do it this way. 
I do think it's non-trivial. Let's keep `RealDependencyLocation` as small as 8-bytes. 

> Alternatively, we could place the `Sourcemap` into the `Dependency` and use `range.to_loc(self.sourcemap)` for location transformation.
Your suggestion sounds promising. Would you please give it a try?

**Comment by shulaoda** [comment]
> Your suggestion sounds promising. Would you please give it a try?

I will complete it in the next PR. Additionally, I propose replacing `RealDependencyLocation` and `SyntheticDependencyLocation` with `RealDependencyRange` and `SyntheticDependencyName` respectively. Our implementation ultimately differs somewhat from `Webpack`.

**Comment by h-a-n-a** [comment]
> > Your suggestion sounds promising. Would you please give it a try?
> 
> I will complete it in the next PR. Additionally, I propose replacing `RealDependencyLocation` and `SyntheticDependencyLocation` with `RealDependencyRange` and `SyntheticDependencyName` respectively. Our implementation ultimately differs somewhat from `Webpack`.

LGTM. You could replace name `RealDependencyRange` with `DependencyRange` and remove `ErrorSpan`. Both of them looks good to me.

**Review by h-a-n-a — APPROVED** [review]
Thanks for the work!

**Pull request merged**
