### PR TITLE
fix(wasm): add fallback for MIME mismatch error in async wasm loading

### PR DESCRIPTION
**Pull request by magic-akari**
## Summary

- webpack/webpack#12259
- webpack/webpack#18016

## Test Plan

TBD

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by magic-akari** [comment]
CI failed. Not sure how to update the test cases.

**Review by ahabhgk — DISMISSED** [review]
Thanks

**Comment by ahabhgk** [comment]
Looks good to me, need resolve conflicts, and it would be better if you can add some tests

**Review by ahabhgk — APPROVED** [review]
Thanks

**Pull request merged**
