### PR TITLE
fix: runtime chunk hash should respect their reference order

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

runtime chunk hash should depend on async entrypoint hash

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Review by LingyuCoder — APPROVED** [review]

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Review by LingyuCoder — APPROVED** [review]

**Pull request merged**
