### PR TITLE
fix: perf

### PR DESCRIPTION
**Pull request by JSerFeng**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by IWANABETHATGUY** [comment]
!bench

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Pull request closed without merging**
