### PR TITLE
refactor: Send module executor tasks to the main task loop

### PR DESCRIPTION
**Pull request by CPunisher**
## Summary

Module executor should not use a separate artifact. To use the artifact of the main task loop, we should send the `importModule` and `loadModule` tasks to the main task loop. This also aligns to webpack.

This could be a pre-requirement of https://github.com/web-infra-dev/rspack/pull/7940

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by jerrykingxyz** [comment]
The `ModuleExecutor` is designed as independent modules, which prevents the side effects generated by `ModuleExecutor` from affecting the module_graph. What is the problem you want to fix in this PR ?

**Comment by CPunisher** [comment]
> The `ModuleExecutor` is designed as independent modules, which prevents the side effects generated by `ModuleExecutor` from affecting the module_graph. What is the problem you want to fix in this PR ?

Is this consistent with webpack? I find that the target modules of `importModule` and `loadModule` may depend on some information of their original modules. Is it possible under current design?

**Comment by jerrykingxyz** [comment]
The `ImportModule` needs to be built and executed using `ModuleExecutor`, but its results should not depend on any modules generated in the "ModuleExecutor".

I think the "LoadModule" should generate a new task to the main task loop, and it should not have any relation with `ModuleExector`.

Could you provide some code example to shows the problem ? I think it should be fixed in the current `ModuleExecutor` implementation.

**Comment by CPunisher** [comment]
> The `ImportModule` needs to be built and executed using `ModuleExecutor`, but its results should not depend on any modules generated in the "ModuleExecutor".
> 
> I think the `LoadModule` should generate a new task to the main task loop, and it should not have any relation with `ModuleExector`.
> 
> Could you provide some code example to shows the problem ? I think it should be fixed in the current `ModuleExecutor` implementation.

One of the problems comes from https://github.com/web-infra-dev/rspack/pull/7940:

> Resolver options of referenced modules should extend their parent modules. Related to https://github.com/web-infra-dev/rspack/blob/833c058da7a9d1c2a15cd9be49065d7c75c7ed7a/tests/webpack-test/cases/loaders/issue-4959/loaders/index.js, "b" is defined in the browser field in package.json, but it's not resolved.

Base on my current implementation, the referenced module should extend the resolve options of its original module in https://github.com/web-infra-dev/rspack/blob/aad975b2bae8b1988fbe9bf0fa269c7a0d824f03/crates/rspack_core/src/compiler/module_executor/entry.rs#L61.

I agree if there's any simpler way to achieve it, since I find this part of code is error-prone.

**Comment by jerrykingxyz** [comment]
Ok, I got it. There are ways to share resolve_option from parent module, like keeping a global map to save the relation from parent module to resolve_option . But I don't think it's a good idea.

I think we should not use module executor to implement loadModule, the better way is to provide a callback when module and sub module are finish in main task loop, like `ModuleExecutor` implementation. I will try to implement it next week.

**Pull request closed without merging**
