### PR TITLE
feat: support compilation.modules[i].dependencies

### PR DESCRIPTION
**Pull request by inottn**
## Summary
https://discord.com/channels/977448667919286283/1076017776583516220/1291085434042060931

## Checklist

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by hardfist** [comment]
we need discuss whether need to support this

**Comment by chenjiahan** [comment]
@hardfist any concerns?

**Comment by hardfist** [comment]
> @hardfist any concerns?

need to discuss how to efficent deal with module graph and chunk graph，will raise a RFC discuss about this in the future

**Comment by SyMind** [comment]
I will track this PR and benchmark the performance of traversing the dependencies.

**Review by SyMind — APPROVED** [review]

**Pull request merged**
