### PR TITLE
feat: add more api

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

- chunkGraph.getModuleId
- fix DynamicEntryPlugin
- external function contextInfo.issuerLayer
- external function getResolve
- deep merge module.rule.resolve
- optimize calculate module rule perf

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
related to https://github.com/web-infra-dev/rspack/issues/7269

**Comment by fi3ework** [comment]
@ahabhgk 

I found that https://github.com/web-infra-dev/rspack/pull/8556 is also implementing `chunkGraph.getModuleId` which is implemented in this PR. And Rslib relies on `getResolve` function to handle external paths. I'm not sure if it's good to rebase this PR now.

Do you mind I cherry-pick the two `getResolve` function commits and append the tests to merge that part first. And the other functions might be cherry-picked in the future for rsnext due to the potential conflict with https://github.com/web-infra-dev/rspack/pull/8556?

cc @SyMind

**Comment by ahabhgk** [comment]
@fi3ework Free feel to cherry-pick

**Comment by ahabhgk** [comment]
Close since most of the changes are already been merged to main by other PR

**Pull request closed without merging**
