### PR TITLE
refactor: streamline filename creation and context preparation for assets in SourceMapDevToolPlugin

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

Maximize performance by parallelizing tasks wherever possible.

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
!bench

**Comment by h-a-n-a** [comment]
Would you please make the title more specific?

**Comment by SyMind** [comment]
@h-a-n-a I've updated the title to be more specific.

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
