### PR TITLE
chore: sync napi function debug

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Summary

Sync https://github.com/h-a-n-a/napi-rs/commit/c1836e5319df63d751368ab0f63187f9d8546680

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
!canary

**Comment by h-a-n-a** [comment]
!canary

**Comment by h-a-n-a** [comment]
!canary

**Comment by hardfist** [comment]
ci failed @h-a-n-a

**Comment by h-a-n-a** [comment]
> ci failed @h-a-n-a 

It's not intended to merge to the main branch.

**Pull request closed without merging**
