### PR TITLE
chore(infra/rust-toolchain): upgrade rust 1.80.0 nightly

### LINKED ISSUE #7341: Upgrade Rust version to 1.80.0 nightly

### PR DESCRIPTION
**Pull request by SoonIter**
## Summary

close #7341 

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
!bench

**Comment by SoonIter** [comment]
!bench

**Comment by SoonIter** [comment]
This pr is big enough at present, we can replace `once_cell` in another pr

**Comment by SoonIter** [comment]
!bench

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
