### PR TITLE
refactor: port inner graph

### LINKED ISSUE #7016: [Bug]: bad case of unused pure expression
### System Info

```sh
  System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.34 GB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 126.0.6478.127
  npmPackages:
    @rspack/cli: 0.7.0 => 0.7.0 
    @rspack/core: 0.7.0 => 0.7.0 
```

### Details

Another problem related to #7012

This problem is included in rspack `0.6.0`-`1.0.0.alpha.0` and `newTreeshaking`-enabled prior-0.6.0 as well.

### js

```js
if (true) {
  const hasConsole = typeof console !== 'undefined';
  const warn = (msg) => {
    if (hasConsole) {
      console.warn(msg)
    }
  }
  warn()
}
```

### rspack.config.js

```js
module.exports = {
  mode: "none",
  devtool: false,
  entry: './src/index.js'.
  optimization: {
    innerGraph: true,
  }
};
```

### Expected

Webpack output as well.

```js
var __webpack_exports__ = {};
if (true) {
  const hasConsole = typeof console !== 'undefined';
  const warn = (msg) => {
    if (hasConsole) {
      console.warn(msg)
    }
  }
  warn()
}
```

### Got

```js
var __webpack_exports__ = {};
if (true) {
  const hasConsole = (/* unused pure expression or super */ null && (typeof console !== 'undefined'));
  const warn = (msg) => {
    if (hasConsole) {
      console.warn(msg)
    }
  }
  warn()
}
```

### Reproduce link

_No response_

### Reproduce Steps

-

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

fix #7016

Implement InnerGraph using parser hook.

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
Are we able to turn on  [this](https://github.com/web-infra-dev/rspack/issues/5554) case?

**Comment by JSerFeng** [comment]
>Are we able to turn on https://github.com/web-infra-dev/rspack/issues/5554 case?

Nope, this pr just port the visit logic of innerGraph

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
