### PR TITLE
feat(rspack_plugin_schemas): http import schema plugin

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
## Summary

Implements the basic capabilities of HTTP URI Plugin 

Example: https://github.com/ScriptedAlchemy/rspack-rust-api

Allows importing of esm http imports and bundling them 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by ahabhgk — APPROVED** [review]

**Comment by ScriptedAlchemy** [comment]
Yes, we should, but I have never done bindings for rspack and am not sure how this is accomplished.

**Comment by hardfist** [comment]
we can merge this first and add binding and js side test in following pr

**Review by hardfist — APPROVED** [review]

**Comment by ScriptedAlchemy** [comment]
@SyMind, would you tag me in the PR so I can read and understand it end-to-end? Then, next time, I'll try to create bindings on my own. 🙃

**Comment by ScriptedAlchemy** [comment]
Yeah that's fine. My  current use cases is with rust projects so I am not blocked by js. But user will want it for sure

**Comment by SyMind** [comment]
@ScriptedAlchemy @hardfist I got it.

**Pull request merged**
