### PR TITLE
fix: nmf before resolve bench regression

### PR DESCRIPTION
**Pull request by ahabhgk**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!bench

**Comment by h-a-n-a** [comment]
!bench

**Pull request merged**
