### PR TITLE
ci: write a comment to issue when canary release is finished.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!canary

**Comment by IWANABETHATGUY** [comment]
It seems that  modification in this pull request does not affect the workflow, how can I test the update in Canary release ? @Boshen

**Comment by IWANABETHATGUY** [comment]
https://github.com/web-infra-dev/rspack/actions/runs/5377830119/jobs/9756823308

**Review by Boshen — APPROVED** [review]

**Review by h-a-n-a — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
Sorry, I forgot esm does not have `__dirname`

**Review by Boshen — APPROVED** [review]

**Pull request merged**
