### PR TITLE
refactor: zod schema and normalized types

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

isomorphism zod schema and normalized types

## Test Plan

- no need

### CODE REVIEW

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
!eco-ci

**Review by hyf0 — DISMISSED** [review]
good job!

**Review by h-a-n-a — DISMISSED** [review]

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
