### PR TITLE
feat: implement styled_components visitor

### PR DESCRIPTION
**Pull request by Asuka109**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by h-a-n-a** [comment]
Would you add some test cases here? 
`packages/rspack/tests/configCases/builtin-swc-loader`

**Comment by Asuka109** [comment]
> Would you add some test cases here? `packages/rspack/tests/configCases/builtin-swc-loader`

Sure, I will add some tests and example later.

**Review by JSerFeng — APPROVED** [review]

**Comment by hardfist** [comment]
please remember update documentation @Asuka109

**Comment by Asuka109** [comment]
> please remember update documentation @Asuka109

@hardfist Okey, maybe in another pr?

**Pull request merged**
