### PR TITLE
fix(3180): panicking when importing empty dependency

### PR DESCRIPTION
**Pull request by Hamzakh777**
## Summary
This PR fixes an issue where Rspacks panics when importing an empty dependency `""`. The solution tries to be as close as possible to Webpacks https://github.com/webpack/webpack/blob/main/lib/NormalModuleFactory.js#L310-L312

Screenshot 2023-10-13 at 15 21 56

Github Issue: #3180 
## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by h-a-n-a** [comment]
Thanks for contributing would you please add a test case?

**Comment by Hamzakh777** [comment]
@h-a-n-a where would I add that test case?

**Comment by hardfist** [comment]
packages/rspack/tests/cases/resolve here

**Comment by Hamzakh777** [comment]
@hardfist @h-a-n-a is there any example I can refer to for testing against failures?

**Comment by hardfist** [comment]
> @hardfist @h-a-n-a is there any example I can refer to for testing against failures?

actually webpack has a test case for it https://github.com/webpack/webpack/tree/main/test/cases/parsing/issue-2006, so we could just enable this test case in rspack

**Comment by Hamzakh777** [comment]
@hardfist wouldn't it be better to use `TraceableError` instead of `internal_error`? As the error is traceable to the original source file

**Comment by hardfist** [comment]
> @hardfist wouldn't it be better to use `TraceableError` instead of `internal_error`? As the error is traceable to the original source file. If we show the file path, plus where exactly in the file the error is coming from that would be a much better DX

I think traceable error seems better now, FYI our traceableError seems have some limitation now and @h-a-n-a is working on refactor the error handle.

**Comment by Hamzakh777** [comment]
@hardfist okay, I'll work on refactoring the code to use `TraceableError`. 
On another note, it seems the test is failing, how does the error propagate from the Rust side to the nodejs side?

**Comment by h-a-n-a** [comment]
> @hardfist okay, I'll work on refactoring the code to use `TraceableError`. On another note, it seems the test is failing, how does the error propagate from the Rust side to the nodejs side?

@Hamzakh777 You can check out [this](https://github.com/web-infra-dev/rspack/blob/455ed97eab7d0e35e77c93314c975b6fd0b6aade/crates/rspack_napi_shared/src/errors.rs#L1) file as a reference. However, at this time, I will not recommend you changing this file as it's under refactor. :-)

**Comment by hardfist** [comment]
since we have not finished align rspack error to webpack error，pass the webpack test without modifying the test case is hard，we need copy this case to rspack tests folder

**Comment by hardfist** [comment]
@Hamzakh777 i can help move the test if you dont mind

**Comment by Hamzakh777** [comment]
sure go for it @hardfist

**Comment by hardfist** [comment]
@Hamzakh777  the ci failed because it failed to generate assets which cause jest can rust the test, so we need to make sure the artifacts generated successfully even resolve failed, I'll investigate furthrer

**Comment by h-a-n-a** [comment]
Sorry for the delay, I will take a look at this issue ASAP.

**Comment by h-a-n-a** [comment]
Ok, I think this test is not quite related to the thing that you've been working on. It relies on the other feature. Would you please add a new test to `packages/rspack/tests/configCases/errors` with something like `empty-dependency-error`

**Comment by h-a-n-a** [comment]
Let's merge this first and solve the error in the refactor error PR :-).

**Comment by h-a-n-a** [comment]
Thanks!

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
