### PR TITLE
feat(create-rspack): add template react-ts

### PR DESCRIPTION
**Pull request by wood3n**
## Summary

add react+typescript template for create-rspack.

### CODE REVIEW

**Comment by wood3n** [comment]
> !canary

sry.i don't understand your mean😂

**Comment by hardfist** [comment]
> > !canary
> 
> sry.i don't understand your mean😂

just trigger a canary release

**Comment by wood3n** [comment]
> > > !canary
> 
> > 
> 
> > sry.i don't understand your mean😂
> 
> 
> 
> just trigger a canary release

ok,i'll change it.

**Comment by wood3n** [comment]
@hardfist excuse me, do i need to change anything? can you help me? 🤣

**Comment by hardfist** [comment]
> @hardfist excuse me, do i need to change anything? can you help me? 🤣

no need, thanks

**Review by hardfist — APPROVED** [review]

**Comment by wood3n** [comment]
> > @hardfist excuse me, do i need to change anything? can you help me? 🤣
> 
> no need, thanks

ok, thanks. 👍

**Pull request merged**
