### PR TITLE
feat: Support module.noParse

### PR DESCRIPTION
**Pull request by OceanPresentChao**
## Summary

support module.noParse. [issue4739](https://github.com/web-infra-dev/rspack/issues/4739)

What does the proposed API of configuration look like?
https://webpack.js.org/configuration/module/#modulenoparse

## Test Plan

run  `npm run test -- -t "no-parse"` in webpack-test

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by xc2** [comment]
hi @OceanPresentChao, are you still working on this? Do you mind me opening a new PR for this?

**Comment by OceanPresentChao** [comment]
> hi @OceanPresentChao, are you still working on this? Do you mind me opening a new PR for this?

Thanks, of course not. I hope this draft may help you work, I will cheer you on

**Comment by xc2** [comment]
> > hi @OceanPresentChao, are you still working on this? Do you mind me opening a new PR for this?
> 
> Thanks, of course not. I hope this draft may help you work, I will cheer you on

thank you for your work(=ﾟωﾟ)ﾉ

**Comment by ahabhgk** [comment]
Complete in https://github.com/web-infra-dev/rspack/pull/5829, thanks anyway

**Pull request closed without merging**
