### PR TITLE
fix: create-rspack default command conflict with help command

### PR DESCRIPTION
**Pull request by PengBoUESTC**
## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [x] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by PengBoUESTC** [comment]
#2241

**Comment by PengBoUESTC** [comment]
`      // Ensure top level options/positionals have been configured:
      const builderResponse = this.#command.runDefaultBuilderOn(this);
      if (isPromise(builderResponse)) {
        builderResponse.then(() => {
          this.#usage.showHelp(level);
        });
        return this;
      }`
https://github.com/yargs/yargs/blob/main/lib/yargs-factory.ts

**Comment by bvanjoi** [comment]
Thank you for your PR, but two details may need to be optimized: can you sign a CLA license, and can you change the commit message to English?

**Comment by PengBoUESTC** [comment]
> Thank you for your PR, but two details may need to be optimized: can you sign a CLA license, and can you change the commit message to English?

done

**Review by bvanjoi — APPROVED** [review]

**Comment by h-a-n-a** [comment]
@PengBoUESTC Would you resolve the conflicts please?

**Comment by PengBoUESTC** [comment]
> @PengBoUESTC Would you resolve the conflicts please?

done

**Pull request merged**
