### PR TITLE
fix: unique name in load script runtime module

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Summary

Support unique name in LoadScriptRuntimeModule

## Test Plan

- Add `packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name`

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Comment by LingyuCoder** [comment]
!diff

**Review by ahabhgk — APPROVED** [review]

**Comment by LingyuCoder** [comment]
!diff

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
