### PR TITLE
chore: add benchmark test for merge queue

### PR DESCRIPTION
**Pull request by jerrykingxyz**
## Summary

Benchmark performance when pushing a pr to merge queue

### CODE REVIEW

**Comment by jerrykingxyz** [comment]
!jerry-test

**Comment by jerrykingxyz** [comment]
!jerry

**Comment by jerrykingxyz** [comment]
!jerry

**Comment by Boshen** [comment]
Let's obverse how PR benchmarks behave before adding this to the merge queue. The merge queue will get overloaded if there are a lot of false positives.

**Pull request merged**
