### PR TITLE
chore: support nodejs benchmark

### PR DESCRIPTION
**Pull request by jerrykingxyz**
## Summary

1. make the `!bench` comment to run benchmark test on Nodejs side
2. run benchmark test on merge queue
3. disable `benchmark-history`

## Glossary

Mean: https://en.wikipedia.org/wiki/Mean
Confidence: https://en.wikipedia.org/wiki/Confidence_interval

## Test Plan

No Test Needed

### CODE REVIEW

**Comment by jerrykingxyz** [comment]
!bench

**Comment by jerrykingxyz** [comment]
!bench

**Comment by jerrykingxyz** [comment]
! bench-js

**Comment by Boshen** [comment]
LGTM. Update the CI trigger and I'll approve.

**Comment by hardfist** [comment]
@jerrykingxyz can you help explain what the table field(such as baseMean, baseConfidence) means?

**Comment by jerrykingxyz** [comment]
> this looks nice, @jerrykingxyz can you help explain what the table field(such as baseMean, baseConfidence) means?

Of course, I have added explanations to the glossary.

**Review by Boshen — APPROVED** [review]

**Pull request merged**
