### PR TITLE
feat(rspack_core): use consistent fxhash for ustr instead of inconsistent ahash

### PR DESCRIPTION
**Pull request by Boshen**
Forking ustr and let's see how it goes ...

relates #5481

### CODE REVIEW

**Comment by Boshen** [comment]
!bench

**Comment by Boshen** [comment]
!eco-ci

**Comment by hardfist** [comment]
I remember github url will break rust cache？

**Comment by Boshen** [comment]
!bench

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
