### PR TITLE
release: 0.3.0

### PR DESCRIPTION
**Pull request by hyf0**
This PR contains the following breaking changes which we're planning to ship in the upcoming minor release.
## Breaking Changes
*  https://github.com/web-infra-dev/rspack/pull/3874
* https://github.com/web-infra-dev/rspack/pull/3873
* https://github.com/web-infra-dev/rspack/pull/3849
* https://github.com/web-infra-dev/rspack/pull/3946
* https://github.com/web-infra-dev/rspack/pull/3961
## CheckList
* [x] Seal all merge request
* [x] Fix all upstream
    * [x] verify startkit
    * [x] nx
    * [x] modern.js
* [x] Update Website Documentation @web-infra-dev/rspack-dx @web-infra-dev/rspack-ux 
* [x] Writing Release Blog @hardfist

### CODE REVIEW

**Comment by h-a-n-a** [comment]
@hyf0 Could you fix the CI? It seems there are some feature conflicting with each other.

**Comment by hyf0** [comment]
> @hyf0 Could you fix the CI? It seems there are some feature conflicting with each other.

Ok. I'll fix it after dinner.

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
I'm not sure which PR label should this PR have, @h-a-n-a @hyf0 any idea

**Comment by hyf0** [comment]
> I'm not sure which PR label should this PR have, @h-a-n-a @hyf0 any idea

I think it's better we merge this PR without squash to keep the commit records. Of cuorse, we should squash some "fix test" commit.

**Comment by hardfist** [comment]
need fix nx tests before release, cc @web-infra-dev/rspack-dx

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by hardfist** [comment]
@mandarini we plan to 0.3.0 in the near future which contains a breaking change https://github.com/web-infra-dev/rspack/pull/3961, which cause nx ecosystem ci failed due to  nx-ecocystem-ci use internal module of rspack(which is forbidden since 0.3.0)
img_v2_d4616bf1-f1c8-4a75-8a57-67277a31be7g
can you help fix it?

**Comment by hardfist** [comment]
!snapshot

**Comment by mandarini** [comment]
@hardfist sorry I was on vacation. I can take a look later today!

**Comment by h-a-n-a** [comment]
!canarrrry

**Comment by h-a-n-a** [comment]
!canary

**Comment by hardfist** [comment]
> Hello @hardfist ! I am just taking a look at this now. The ecosystem tests seem to be passing, but we still have these two internal imports:
> 
> * `import Watching from '@rspack/core/dist/watching';` ([here](https://github.com/nrwl/nx-labs/blob/main/packages/rspack/src/executors/rspack/rspack.impl.ts#L4)
> * `import { DevServer } from '@rspack/core/dist/config';` ([here](https://github.com/nrwl/nx-labs/blob/main/packages/rspack/src/executors/dev-server/dev-server.impl.ts#L7))
> 
> Do you have any suggestions as to how we should fix this? Or is it not needed any more?

these two seems are types so maybe you can manualy configure this type and we will export this type in 0.3

**Comment by jerrykingxyz** [comment]
!bench

**Comment by hardfist** [comment]
!eco-ci

**Comment by mandarini** [comment]
@hardfist I see that it's still failing :/

**Comment by hardfist** [comment]
> @hardfist I see that it's still failing :/
it's caused by another problem https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/5948557228/job/16132574172#step:8:919, I will try to fix it

**Comment by mandarini** [comment]
fwit I ran it locally and it passed! :) https://app.warp.dev/block/OCSw0Ex0YlCdR6pzTvQ4Pl

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
!eco-ci

**Comment by hardfist** [comment]
finally pass

**Pull request merged**
