### PR TITLE
fix(rspack_plugin_html): align rspack_plugin_html inject option behavior with html-webpack-plugin

### LINKED ISSUE #5544: rspack_plugin_html inject option behaves differently from html-webpack-plugin
### System Info

can ignore this as it does not matter.

### Details

I encountered style issues when migrating our webpack projects to rspack.

After investigation, I found that `rspack.HtmlRspackPlugin` always follows the `inject: 'body'` option to inject the main CSS chunk at the end the of body [^rspack_plugin_html]. However, both `@rspack/html-plugin` and `html-webpack-plugin` always inject the main CSS chunk into the head regardless of the `inject` option [^rspack-plugin-html] [^html-webpack-plugin].

Async CSS chunks are always appended to the head. Therefore, when `inject: 'body'`, in the code generated by webpack, selectors with the same weight in async chunks will always take precedence over those in the main chunk, while in the code generated by rspack it is the opposite.

| html-webpack-plugin                               | rspack_plugin_html                              |
|---------------------------------------------------|-------------------------------------------------|
| html-webpack-plugin | rspack_plugin_html |

[^rspack_plugin_html]: [rspack/crates/rspack_plugin_html/src/plugin.rs#L150](https://github.com/web-infra-dev/rspack/blob/4792bb7365fc750873451b23bac4cad71d910ec3/crates/rspack_plugin_html/src/plugin.rs#L150)
[^rspack-plugin-html]: [rspack/rspack-plugin-html/src/index.ts#L1016](https://github.com/web-infra-dev/rspack/blob/64939a7136234496b8336114e18b95dce38ab610/packages/rspack-plugin-html/src/index.ts#L1016)
[^html-webpack-plugin]: [html-webpack-plugin/index.js#L927](https://github.com/jantimon/html-webpack-plugin/blob/ebfa1cecdace8a75a6a167e70aac4f0e0ad90121/index.js#L927)

### Reproduce link

https://github.com/nilptr/rspack_plugin_html-inject-option-issue

### Reproduce Steps

1. clone the repo and run `pnpm install`
2. run `pnpm run dev:webpack` and `pnpm run dev:rspack` separately
3. check the "Timer" tab

### PR DESCRIPTION
**Pull request by nilptr**
## Summary

This is pull request to fix #5544 

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by h-a-n-a** [comment]
Looks good to me

**Comment by nilptr** [comment]
I rebased master. Please check again. Thanks

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
!canary

**Review by h-a-n-a — APPROVED** [review]

**Comment by h-a-n-a** [comment]
Thank you!

**Pull request merged**
