### PR TITLE
feat(devtool): add "eval" support

### PR DESCRIPTION
**Pull request by xc2**
## Summary

support "eval" only output for devtool.

please feel free to close the pr if it is not planned.

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Review by ahabhgk — APPROVED** [review]
looks good to me, @SyMind cc

**Comment by SyMind** [comment]
!bench

**Comment by SyMind** [comment]
@ahabhgk Great work! This looks good to me.

**Comment by ahabhgk** [comment]
Thanks!

**Pull request merged**
