### PR TITLE
fix: add sourcemap file to chunk.auxiliaryFiles (#3253)

### PR DESCRIPTION
**Pull request by flyingalex**
## Summary
fix: add sourcemap file to chunk.auxiliaryFiles (#3253)

## Test Plan
I created a demo to test it
https://github.com/flyingalex/rspack-for-react-test-verification
## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by flyingalex** [comment]
@hardfist Can you help take a look at this MR, thanks a lot

**Comment by SyMind** [comment]
@flyingalex Thank you. There is an issue with the Rust CI checks. Could you please take a look at it?

**Comment by flyingalex** [comment]
@SyMind Hey, after checked the main branch, I found its already fixed by your codes here: https://github.com/web-infra-dev/rspack/blob/f3dc1fd3a31984d5224405c7f6d583da239f8bcf/crates/rspack_plugin_devtool/src/lib.rs#L554-L556

I will close this, thanks for checking, maybe you also can close #3253, since its not valid anymore

**Comment by jbroma** [comment]
sourcemaps are still not present in `chunk.auxiliaryFiles` in 0.5.7, can we reopen this?

**Comment by jbroma** [comment]
@SyMind @hulin32 sourcemaps are still not present in `chunk.auxiliaryFiles` in 0.5.7, can we reopen this?

**Comment by hulin32** [comment]
Hello @jbroma Can you tell me what's your requirement? what are you going to do with it? true it's not in `chunk.auxiliaryFiles`, I opened this PR caused by the issue in #3253, although its not add sourcemap to `chunk.auxiliaryFiles`, but it's already fixed the issue provided in that description, I will continue to work on it if its make sense, thanks

**Comment by jbroma** [comment]
@hulin32 I'm expertimenting with `rspack` integration with [Re.Pack](https://github.com/callstack/repack) and we use `chunk.auxiliaryFiles` for the following purposes:
- our `ManifestPlugin` includes sourcemap from `chunk.auxiliaryFiles` in it's output.
- our `OutputPlugin` uses `chunk.auxiliaryFiles` to obtain sourcemap filename to copy to the target device assets

Since `webpack.SourceMapDevtoolPlugin` includes sourcemap into `chunk.auxiliaryFiles`, it should be the same in `rspack`, so it would be good to continue with this PR.

Sidenote: naturally, we could work around this by utilizing `output.sourceMapFilename` template and construct the sourcemap filename from scratch, so it's not a blocker of any kind.

**Comment by hulin32** [comment]
@jbroma hey, thanks for your info, I will find time to continue to work on it

**Pull request closed without merging**
