### PR TITLE
feat: the missing part of loader

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Summary

Almost the last missing piece of the webpack loader(runner) implementation.
In older version of rspack, rspack does not support dispatching 
JavaScript pitching loader and native pitching loader at the same time.

This PR refactored the original loader-runner to use a state machine 
sharing across native and JavaScript runtimes. Loader runners on both
JavaScript and native side will yield to each other if the next loader has
a different type.

closes https://github.com/web-infra-dev/rspack/issues/5735
closes https://github.com/web-infra-dev/rspack/issues/6457

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
!bench

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
!bench

**Review by LingyuCoder — APPROVED** [review]

**Pull request merged**
