### PR TITLE
feat: add initial angular support

### PR DESCRIPTION
**Pull request by edusperoni**
## Summary

Angular support is hindered by a couple of missing hooks (beforeCompile, finishModules), missing createChildCompiler, missing NormalModule and its loader hook, and finally, normalModuleFactory (not exposed yet) from the `thisCompilation` hook.

This PR addresses `beforeCompile` (not passing the params), `finishModules`, `NormalModule` `loader` hook and `createChildCompiler` (initial implementation). The angular compilation still fails due to the unexposed `normalModuleFactory`

## Related issue (if exists)

https://github.com/web-infra-dev/rspack/issues/2099

## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [x] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by edusperoni** [comment]
@h-a-n-a cla signed! I'm not sure what other package besides `@rspack/core` would be affected by my changes, could you provide any guidance on that?

**Comment by h-a-n-a** [comment]
> @h-a-n-a cla signed! I'm not sure what other package besides `@rspack/core` would be affected by my changes, could you provide any guidance on that?

@edusperoni Sure! I'd love to. It's quite late in east Asia, so I guess I will take a look on tomorrow :).

**Comment by edusperoni** [comment]
@h-a-n-a the missing features are in the `thisCompilation` hook. It exists but it doesn't pass the moduleFactories in the arguments, so angular fails to compile (https://github.com/angular/angular-cli/blob/main/packages/ngtools/webpack/src/resource_loader.ts#L182).

I'll update my changeset later today

**Comment by edusperoni** [comment]
Further progress on this:
1- merged latest main on it
2- merged https://github.com/web-infra-dev/rspack/pull/2356 into https://github.com/edusperoni/rspack/tree/chore/create-angular2

with that PR, it gets further, and now we are missing 2 hooks. One is the `readResourceForScheme` of the NormalModule hooks, and the other is the `additionalAssets` hook

**Comment by edusperoni** [comment]
closing in favor of #3009

**Pull request closed without merging**
