### PR TITLE
chore: update swc

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

Update swc to solve minify [issue](https://github.com/swc-project/swc/issues/8886)

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by JSerFeng** [comment]
!eco-ci

**Comment by LingyuCoder** [comment]
another issue need to upgrade swc: https://github.com/web-infra-dev/rspack/issues/6488

**Comment by JSerFeng** [comment]
> another issue need to upgrade swc: https://github.com/web-infra-dev/rspack/issues/6488

I think version in this pr is okay

**Comment by SyMind** [comment]
!eco-ci

**Review by SyMind — APPROVED** [review]

**Pull request merged**
