### PR TITLE
chore: remove rspack-dev-middleware

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

This PR remove the code of rspack-dev-middleware 

In code, rspack-dev-middleware already labeled as deprecated, we might also need to [deprecate the package](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-an-entire-package) @hardfist

### CODE REVIEW

**Comment by hyf0** [comment]
If this is a breaking change, please open a discussion first.

**Comment by ahabhgk** [comment]
Technically, this will not break anything

**Comment by hyf0** [comment]
> Technically, this will not break anything

If this is not a breaking change, you could just merge this commit to the main branch.

**Comment by hardfist** [comment]
please rebase

**Review by hardfist — APPROVED** [review]

**Pull request closed without merging**
