### PR TITLE
release: v0.5.0 proposal

### PR DESCRIPTION
**Pull request by hardfist**
## Summary
# 0.4.x Deprecate Changes
- [x] rspackFuture.disableApplyEntryLazily https://github.com/web-infra-dev/rspack/issues/4898 @ahabhgk 
# 0.5.0 Breaking Changes
- [x] #4822 
- [x] align default resolve.extension with webpack https://github.com/web-infra-dev/rspack/pull/5184 @h-a-n-a 
- [x] https://github.com/web-infra-dev/rspack/pull/5089 @Boshen 
- [x] remove legacy default transformer code in 0.5 https://github.com/web-infra-dev/rspack/pull/5185 @h-a-n-a 
- [x] remove legacy sass_loader code in 0.5 https://github.com/web-infra-dev/rspack/pull/5177 @ahabhgk 
- [x] make react-refresh peerDeps in 0.5 https://github.com/web-infra-dev/rspack/pull/5228 @ahabhgk 
- [x] make @swc/helpers peerDeps in 0.5 https://github.com/web-infra-dev/rspack/pull/5228 @ahabhgk 
- [x] remove old splitChunks code in 0.5 https://github.com/web-infra-dev/rspack/pull/5208 @JSerFeng 
- [x] remove experiments.incrementalRebuild option https://github.com/web-infra-dev/rspack/pull/5225 @jerrykingxyz 
- [x] make `rspackFuture.disableApplyEntryLazily: true` by default https://github.com/web-infra-dev/rspack/pull/5179 @ahabhgk 
- [x] remove `devServer.hot` from core, dev-server should apply HotModuleReplacementPlugin manually https://github.com/web-infra-dev/rspack/pull/5193 @ahabhgk 
- [x] remove `builtins.noEmitAssets`, `builtins.presetEnv`, `builtins.decorator`, `builtins.devFriendlySplitChunks`, `builtins.react`, `builtins.pluginImport`, `builtins.emotion`, `builtins.relay`, `builtins.html`, `builtins.copy`, `builtins.minifyOptions` https://github.com/web-infra-dev/rspack/pull/5207 @ahabhgk

# Highlight
- [ ] Module Federation Support @ahabhgk 

# Performance Regression Check
- [ ] check whether introduce performance regression in real world projects

## Require Documentation?

- [ ] No
- [x] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
!eco-ci

**Comment by h-a-n-a** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4821** <a href="https://app.graphite.dev/github/pr/web-infra-dev/rspack/4821?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/web-infra-dev/rspack/4821?utm_source=stack-comment).

**Comment by ahabhgk** [comment]
!eco-ci
!canary

**Comment by hardfist** [comment]
!bench

**Comment by ahabhgk** [comment]
!eco-ci
!canary

**Comment by ahabhgk** [comment]
!eco-ci rsbuild --suite-branch upgrade-rspack-0.5

**Comment by ahabhgk** [comment]
!eco-ci
!canary

**Comment by ahabhgk** [comment]
!bench

**Comment by ahabhgk** [comment]
!canary

**Comment by hardfist** [comment]
!eco-ci

**Comment by ahabhgk** [comment]
it will automatically update the version in template now https://github.com/web-infra-dev/rspack/pull/5261/files#diff-238099b4330f0cc69c2eaf26f617b5fb51b872e25511b2691ed81ab98ab64986

**Review by ahabhgk — APPROVED** [review]

**Pull request merged**
