### PR TITLE
refactor: runtime module

### PR DESCRIPTION
**Pull request by underfin**
## Summary

- avoid runtime unnecessary allocation
- add runtime module code generation cache
-  runtime module implement module trait

## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by underfin** [comment]
!bench

**Comment by IWANABETHATGUY** [comment]
!bench

**Comment by underfin** [comment]
!bench

**Comment by IWANABETHATGUY** [comment]
I think the reason of CI failing maybe related to https://github.com/community/community/discussions/13496

**Review by h-a-n-a — APPROVED** [review]

**Pull request merged**
