### PR TITLE
refactor: refactor remove parent modules

### LINKED ISSUE #5456: Refactor remove availableModules
### What problem does this feature solve?

Currently removeAvailableModules needs an extra visit whole chunkGroup, and collects intersection modules, that's a huge cost, in some big projects, it costs about 1/3 time of the total build.

### What does the proposed API of configuration look like?

Refactor code splitting

### PR DESCRIPTION
**Pull request by JSerFeng**
close #5456

## Summary

refactor code-splitting, calculate available modules right in the process of building chunk graph.

This can improve performance significantly in complex chunk graph

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!bench

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!canary

**Comment by JSerFeng** [comment]
!bench

**Review by ahabhgk — APPROVED** [review]

**Comment by JSerFeng** [comment]
!eco

**Pull request merged**
