### PR TITLE
feat: support more methods for `errors` and `warnings` in `Compilation`

### PR DESCRIPTION
**Pull request by coder-xiaotian**
… (6222)

## Summary

Proxy array's method to compilation.rs for fix [this issue](https://github.com/web-infra-dev/rspack/issues/6222). I don't know how to transfer functions between js and rust, so I didn't proxy the sort method of the array.

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by h-a-n-a** [comment]
I didn't see which issue you're trying to resolve. The link you provided seems not correct.

**Comment by coder-xiaotian** [comment]
> I didn't see which issue you're trying to resolve. The link you provided seems not correct.

Sorry, I made a mistake. Is this [issue](https://github.com/web-infra-dev/rspack/issues/6222)

**Comment by coder-xiaotian** [comment]
> > > I didn't see which issue you're trying to resolve. The link you provided seems not correct.
> > 
> > 
> > Sorry, I made a mistake. Is this [issue](https://github.com/web-infra-dev/rspack/issues/6222)
> 
> Looks good to me. Would you please fix `get warnings() in Compilation` too?

Ok, of course!

**Comment by coder-xiaotian** [comment]
@h-a-n-a I have added tests for map function.

**Review by h-a-n-a — APPROVED** [review]
Thank you

**Comment by colinaaa** [comment]
This patch made a breaking change by changing the type of `compilation.errors` to `any`.

In `@rspack/core@0.6.3`:

```ts
class Compilation {
    get errors(): {
        push: (...errs: (Error | JsStatsError | string)[]) => void;
        readonly length: number;
        [Symbol.iterator](): {
            next(): {
                done: boolean;
                value?: undefined;
            } | {
                value: JsStatsError;
                done: boolean;
            };
        };
    };
    get warnings(): {
        push: (...warns: (Error | JsStatsError)[]) => void;
        [Symbol.iterator](): {
            next(): {
                done: boolean;
                value?: undefined;
            } | {
                value: import("@rspack/binding").JsStatsWarning[];
                done: boolean;
            };
        };
    };
}
```

In `@rspack/core@0.6.4`:

```ts
class Compilation {
    get errors(): any;
    get warnings(): JsStatsWarning[];
}

**Comment by coder-xiaotian** [comment]
> @rspack/core

The error of rspack is different from WebpackError, and I don't know how to be compatible, so I gave it an any type. Can you give me some advice.🌟

**Comment by colinaaa** [comment]
I think `JsStatsError` would work.

**Comment by coder-xiaotian** [comment]
> I think `JsStatsError` would work.

you can open an issue.

**Pull request merged**
