### PR TITLE
feat(es): allow parse js hashbang syntax

### PR DESCRIPTION
**Pull request by magic-akari**
## Summary

- Closes: #4427

## Test Plan

crates/rspack_loader_swc/tests/fixtures/hashbang added.
If there are any additional locations where test cases need to be added, please inform me.

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by LingyuCoder** [comment]
This modification only works when using builtin:swc-loader, may consider adding it in `crates/rspack_plugin_javascript/src/ast/parse.rs` to prevent compilation failure when not using builtin:swc-loader.

And it would be better if you could align the addition of comments with [webpack](https://github.com/webpack/webpack/blob/v5.89.0/lib/CompatibilityPlugin.js#L165)

**Comment by magic-akari** [comment]
@LingyuCoder Do you have any suggestions about test cases?

**Comment by LingyuCoder** [comment]
> @LingyuCoder Do you have any suggestions about test cases?

It is recommended to add test cases to ensure that the bundled script runs correctly. You can reuse webpack's test cases by removing `webpack-test/cases/parsing/hashbang/test.filter.js`. And also you can add additional test cases in the `packages/rspack/tests` directory.

**Comment by LingyuCoder** [comment]
Thanks

**Pull request merged**
