### PR TITLE
feat: isomorphism mf 1.0 and 1.5

### PR DESCRIPTION
**Pull request by ahabhgk**
## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by ahabhgk** [comment]
!canary

**Comment by ahabhgk** [comment]
!canary

**Comment by ahabhgk** [comment]
!canary

**Comment by ahabhgk** [comment]
!canary

**Review by JSerFeng — APPROVED** [review]

**Pull request merged**
