### PR TITLE
refactor: dependency request use JsWord

### PR DESCRIPTION
**Pull request by underfin**
## Summary
Because `importVarMap` will clone request as key, so here use JsWord to avoid string clone.

## Test Plan
It's not requried

### CODE REVIEW

**Comment by underfin** [comment]
!bench

**Comment by ahabhgk** [comment]
Hard to say which is better since JsWord is hard for migrating to oxc and there is basically no change in benchmark

**Comment by jerrykingxyz** [comment]
!bench

**Comment by jerrykingxyz** [comment]
!bench

**Comment by jerrykingxyz** [comment]
!bench

**Comment by jerrykingxyz** [comment]
!bench

**Comment by hardfist** [comment]
close for stale

**Pull request closed without merging**
